//! Writing `appearance.lua` and getting Hyprland to load it.
//!
//! One file for both halves — the `hl.config` overlay and the
//! `hl.animation` calls — because both are last-wins overrides sourced
//! from the same require line, so splitting them would buy nothing but a
//! second thing to keep in sync.

use crate::animations::{self, Animations};
use crate::catalog::CATALOG;
use crate::storage::Appearance;
use hyprforge_core::hlconfig::{codegen, Settings};
use std::path::Path;

pub use hyprforge_core::apply_lua::ApplyError;

/// Named in the generated file's header and in the apply/rollback
/// messages, so a user who meets either knows which screen owns it.
const SUBJECT: &str = "appearance settings";

pub fn generate(appearance: &Appearance, known_curves: Option<&[String]>) -> String {
    let mut out = codegen::generate(&appearance.settings, &CATALOG, SUBJECT);
    let anim = animations::generate(&appearance.animations, known_curves);
    if !anim.is_empty() {
        out.push('\n');
        out.push_str(&anim);
    }
    out
}

pub fn apply(
    lua_path: &Path,
    appearance: &Appearance,
    known_curves: Option<&[String]>,
) -> Result<(), ApplyError> {
    let empty = Appearance {
        settings: Settings::default(),
        animations: Animations::default(),
    };
    hyprforge_core::apply_lua::apply(hyprforge_core::apply_lua::GeneratedFile {
        path: lua_path,
        contents: &generate(appearance, known_curves),
        empty: &generate(&empty, known_curves),
        subject: SUBJECT,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::animations::Animation;
    use hyprforge_core::hlconfig::Value;

    #[test]
    fn both_halves_share_one_file() {
        let mut settings = Settings::default();
        settings.set("decoration:rounding", Value::Int(10));
        let mut animations = Animations::default();
        animations.set(
            "windows",
            Animation {
                enabled: true,
                speed: 4.79,
                bezier: "easeOutQuint".to_string(),
                style: String::new(),
            },
        );
        let lua = generate(&Appearance { settings, animations }, None);
        assert!(lua.contains("hl.config({"), "{lua}");
        assert!(lua.contains("rounding = 10,"), "{lua}");
        assert!(lua.contains("hl.animation({ leaf = [[windows]]"), "{lua}");
    }

    /// The empty file still has to be valid Lua: it's written at setup,
    /// before anything is configured, and `require()` of a broken file is
    /// an error on the user's next reload.
    #[test]
    fn an_empty_set_is_still_a_loadable_file() {
        let lua = generate(&Appearance::default(), None);
        assert!(lua.starts_with("-- Generated by Hyprforge"));
        assert!(!lua.contains("hl.config"), "{lua}");
        assert!(!lua.contains("hl.animation"), "{lua}");
    }

    #[test]
    fn animations_alone_still_produce_a_file() {
        let mut animations = Animations::default();
        animations.set(
            "fade",
            Animation { enabled: true, speed: 3.0, bezier: String::new(), style: String::new() },
        );
        let lua = generate(&Appearance { settings: Settings::default(), animations }, None);
        assert!(lua.contains("hl.animation"), "{lua}");
        assert!(!lua.contains("hl.config"), "{lua}");
    }
}
