//! Writing `session.lua` and getting Hyprland to load it.
//!
//! The write/reload/verify/rollback sequence is
//! [`hyprforge_core::apply_lua`], shared with every other Lua module.
//! This file contributes the order the four sections appear in, which is
//! chosen for a reader rather than for Hyprland:
//!
//! 1. environment — the things everything else inherits
//! 2. permissions — security rules, near the top where they're visible
//! 3. gestures
//! 4. autostart — last, because it's the part people scroll to

use crate::storage::Session;
use crate::{autostart, environment, gestures, permissions};
use std::path::Path;

pub use hyprforge_core::apply_lua::ApplyError;

const SUBJECT: &str = "session settings";

const HEADER: &str = "-- Generated by Hyprforge. Do not edit by hand — changes will be\n-- overwritten the next time session settings are saved in the Hyprforge\n-- Settings app.\n";

/// Renders the whole file.
///
/// `existing_gestures` are the ones already declared in the user's own
/// config: Hyprland refuses a gesture that duplicates an earlier one, and
/// a refused call aborts the chunk, so a clash has to be filtered out
/// here rather than discovered at reload.
pub fn generate(session: &Session, existing_gestures: &[gestures::Gesture]) -> String {
    let mut out = String::from(HEADER);
    for (label, body) in [
        ("Environment", environment::generate(&session.environment)),
        ("Permissions", permissions::generate(&session.permissions)),
        ("Gestures", gestures::generate(&session.gestures, existing_gestures)),
        ("Autostart", autostart::generate(&session.autostart)),
    ] {
        if body.is_empty() {
            continue;
        }
        out.push_str(&format!("\n-- {label}\n"));
        out.push_str(&body);
    }
    out
}

pub fn apply(
    lua_path: &Path,
    session: &Session,
    existing_gestures: &[gestures::Gesture],
) -> Result<(), ApplyError> {
    hyprforge_core::apply_lua::apply(hyprforge_core::apply_lua::GeneratedFile {
        path: lua_path,
        contents: &generate(session, existing_gestures),
        empty: &generate(&Session::default(), existing_gestures),
        subject: SUBJECT,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_empty_session_is_still_a_loadable_file() {
        let out = generate(&Session::default(), &[]);
        assert!(out.starts_with("-- Generated by Hyprforge"));
        assert!(!out.contains("hl."), "{out}");
    }

    #[test]
    fn sections_are_labelled_and_ordered_for_a_reader() {
        let mut session = Session::default();
        session.autostart.programs.push(autostart::Program {
            command: "waybar".into(),
            enabled: true,
            ..Default::default()
        });
        session.environment.variables.push(environment::Variable {
            name: "GTK_THEME".into(),
            value: "Dracula".into(),
            enabled: true,
        });
        let out = generate(&session, &[]);
        assert!(out.contains("-- Environment"), "{out}");
        assert!(out.contains("-- Autostart"), "{out}");
        assert!(
            out.find("hl.env") < out.find("hl.on"),
            "environment comes before autostart: {out}"
        );
    }

    /// An empty section is omitted entirely rather than left as a bare
    /// heading over nothing.
    #[test]
    fn an_empty_section_leaves_no_heading() {
        let mut session = Session::default();
        session.environment.variables.push(environment::Variable {
            name: "GTK_THEME".into(),
            value: "Dracula".into(),
            enabled: true,
        });
        let out = generate(&session, &[]);
        assert!(!out.contains("-- Autostart"), "{out}");
        assert!(!out.contains("-- Gestures"), "{out}");
    }
}
