//! Renders the live, settled layout as static `hl.monitor()` calls —
//! `monitors.lua`, sourced via `require("hyprforge/monitors")`.
//!
//! This is deliberately not a full re-implementation of the daemon's
//! fingerprint-matching logic: it's a "last known good" snapshot Hyprland
//! can apply on its own startup/reload, so a saved layout survives even
//! when `hyprforge-displayd` isn't running to reassert it over
//! `wlr-output-management-v1`. The daemon still owns the live, adaptive
//! behavior — this file is only ever regenerated wholesale, never hand
//! -edited or read back.

use crate::types::{Head, Transform};
use hyprforge_core::geometry::nearest_valid_scale;
use std::collections::HashMap;

const HEADER: &str = "-- Generated by Hyprforge. Do not edit by hand — changes will be\n-- overwritten the next time the display daemon settles a layout.\n";

/// One output as it should be described to Hyprland. `selector` is
/// Hyprland's own `desc:<description>` string (or a bare connector name as
/// a fallback) — never displayd's own EDID description, which is not
/// guaranteed to match how Hyprland formats the same field.
#[derive(Debug, Clone, PartialEq)]
pub struct MonitorEntry {
    pub selector: String,
    pub enabled: bool,
    /// `None` only when `enabled` is false — a disabled output's mode is
    /// irrelevant.
    pub mode: Option<(i32, i32, i32)>,
    pub position: (i32, i32),
    /// Already snapped to an achievable `k/120` scale — the caller's job,
    /// same division of concerns `HeadRecord::from_head` uses in
    /// `profile.rs`. Emitting the raw wire value here would write an odd
    /// off-preset number into a file meant to be a stable fallback.
    pub scale: f64,
    pub transform: Transform,
}

/// Builds the entries to render from the live, settled heads plus
/// Hyprland's own connector→description map (see
/// [`crate::hyprctl_monitors::connector_descriptions`] for why that map
/// can't come from `Head` itself).
///
/// A connector missing from `descriptions` — `hyprctl` unreachable, or that
/// output simply has no description to report — falls back to the bare
/// connector name, same rule `Monitor::rule_selector` uses in
/// `hyprforge-windowrules`. That's a weaker selector (doesn't survive a
/// replug), but still strictly better than omitting the output from the
/// fallback file entirely.
pub fn entries_from_heads(heads: &[Head], descriptions: &HashMap<String, String>) -> Vec<MonitorEntry> {
    heads
        .iter()
        .map(|head| {
            let selector = match descriptions.get(&head.connector) {
                Some(desc) if !desc.trim().is_empty() => format!("desc:{}", desc.trim()),
                _ => head.connector.clone(),
            };
            let mode = head.effective_mode().map(|m| (m.width, m.height, m.refresh_mhz));
            let (width, height) = mode.map(|(w, h, _)| (w, h)).unwrap_or((0, 0));
            MonitorEntry {
                selector,
                enabled: head.enabled,
                mode: head.enabled.then_some(mode).flatten(),
                position: head.position,
                scale: nearest_valid_scale(width, height, head.scale),
                transform: head.transform,
            }
        })
        .collect()
}

/// Renders `entries` to a complete `monitors.lua` body.
///
/// **Disabled outputs are described in a comment, never as a rule.** This
/// is the one place the fallback deliberately does not mirror the live
/// layout, and it is the difference between a cosmetic wrong and an
/// unusable machine:
///
/// A rule is matched by whatever is plugged in when Hyprland *reads* this
/// file, not by what was plugged in when the daemon wrote it. Dock with
/// the lid closed and the internal panel is legitimately disabled, so
/// `disabled = true` for it and a normal rule for the external is an
/// accurate description of that moment. Undock, then boot before the
/// daemon starts: the external's rule matches nothing, the internal's
/// still matches — and the only display present is switched off, by the
/// very file whose job is to stop you losing your display when the daemon
/// is not running.
///
/// Omitting the rule instead means Hyprland applies its own default and
/// the panel comes up. If the daemon then starts and the profile really
/// does want it off, it turns it off a second later over
/// `wlr-output-management-v1`. So the cost is a panel that is briefly on
/// when it should be off; the cost of the alternative is a black screen
/// with no way back that does not involve a TTY.
pub fn generate(entries: &[MonitorEntry]) -> String {
    let mut out = String::from(HEADER);
    out.push('\n');
    for entry in entries.iter().filter(|e| !e.enabled) {
        // Recorded, not silently dropped: someone reading this file needs
        // to be able to tell "displayd has never seen that output" from
        // "displayd knows about it and is leaving it to Hyprland".
        out.push_str(&format!(
            "-- {} is disabled in the live layout. Deliberately left to Hyprland's\n             -- default here: a `disabled` rule would also match when it is the only\n             -- display present, and switch off the screen this file exists to save.\n",
            entry.selector,
        ));
    }
    for entry in entries.iter().filter(|e| e.enabled) {
        out.push_str(&render(entry));
    }
    out
}

fn render(entry: &MonitorEntry) -> String {
    debug_assert!(entry.enabled, "generate filters disabled entries out");
    let mode = match entry.mode {
        Some((width, height, refresh_mhz)) => {
            format!("{width}x{height}@{:.2}", refresh_mhz as f64 / 1000.0)
        }
        None => "preferred".to_string(),
    };
    let (x, y) = entry.position;
    format!(
        "hl.monitor({{ output = {}, mode = {}, position = {}, scale = {}, transform = {} }})\n",
        lua_string(&entry.selector),
        lua_string(&mode),
        lua_string(&format!("{x}x{y}")),
        entry.scale,
        transform_index(entry.transform),
    )
}

/// Hyprland's `transform` field is the `wl_output.transform` enum's own
/// integer values (0–7) — the same numbering `backend/wlr.rs` converts
/// to/from at the protocol boundary, spelled out explicitly here too rather
/// than relied on as an implicit enum discriminant.
fn transform_index(t: Transform) -> u8 {
    match t {
        Transform::Normal => 0,
        Transform::Rotate90 => 1,
        Transform::Rotate180 => 2,
        Transform::Rotate270 => 3,
        Transform::Flipped => 4,
        Transform::Flipped90 => 5,
        Transform::Flipped180 => 6,
        Transform::Flipped270 => 7,
    }
}

/// Quotes with a Lua long bracket, which needs no escaping, so a `desc:`
/// string containing regex-like or quote characters can never break the
/// generated call's own parse.
///
/// The one implementation all three generating crates share — this crate's
/// former copy got the fallback condition wrong in the same way the other
/// two did. See [`hyprforge_core::lua`].
use hyprforge_core::lua::lua_string;

#[cfg(test)]
mod tests {
    use super::*;

    fn enabled_entry() -> MonitorEntry {
        MonitorEntry {
            selector: "desc:BOE 0x0BC9".to_string(),
            enabled: true,
            mode: Some((2560, 1600, 60000)),
            position: (0, 0),
            scale: 1.25,
            transform: Transform::Normal,
        }
    }

    fn head(connector: &str, enabled: bool) -> Head {
        let mode = crate::types::Mode { width: 2560, height: 1600, refresh_mhz: 60000, preferred: true };
        Head {
            connector: connector.to_string(),
            identity: crate::types::Identity::default(),
            description: "displayd's own EDID description (must not be used)".to_string(),
            modes: vec![mode],
            current_mode: Some(mode),
            position: (0, 0),
            transform: Transform::Normal,
            scale: 1.25,
            enabled,
        }
    }

    #[test]
    fn a_known_connector_gets_a_desc_selector_from_hyprctls_own_map() {
        let heads = vec![head("eDP-1", true)];
        let descriptions = HashMap::from([("eDP-1".to_string(), "BOE 0x0BC9".to_string())]);
        let entries = entries_from_heads(&heads, &descriptions);
        assert_eq!(entries[0].selector, "desc:BOE 0x0BC9");
    }

    /// Displayd's own `Head.description` must never leak into the
    /// selector — see the module docs for why the two aren't
    /// interchangeable.
    #[test]
    fn an_unknown_connector_falls_back_to_the_bare_connector_not_displayds_description() {
        let heads = vec![head("eDP-1", true)];
        let entries = entries_from_heads(&heads, &HashMap::new());
        assert_eq!(entries[0].selector, "eDP-1");
    }

    #[test]
    fn a_disabled_head_carries_no_mode() {
        let heads = vec![head("eDP-1", false)];
        let entries = entries_from_heads(&heads, &HashMap::new());
        assert!(!entries[0].enabled);
        assert_eq!(entries[0].mode, None);
    }

    #[test]
    fn scale_is_snapped_to_an_achievable_120th_not_the_raw_wire_value() {
        let mut heads = vec![head("eDP-1", true)];
        // Not a valid k/120 for 2560x1600 — nearest_valid_scale must correct
        // it rather than passing it straight through.
        heads[0].scale = 1.5;
        let entries = entries_from_heads(&heads, &HashMap::new());
        assert_ne!(entries[0].scale, 1.5);
    }

    #[test]
    fn empty_input_is_just_the_header() {
        let lua = generate(&[]);
        assert!(lua.starts_with("-- Generated by Hyprforge"));
        assert!(!lua.contains("hl.monitor"));
    }

    #[test]
    fn renders_an_enabled_output() {
        let lua = generate(&[enabled_entry()]);
        assert!(
            lua.contains(
                "hl.monitor({ output = [[desc:BOE 0x0BC9]], mode = [[2560x1600@60.00]], \
                 position = [[0x0]], scale = 1.25, transform = 0 })"
            ),
            "got: {lua}"
        );
    }

    #[test]
    fn a_disabled_output_never_becomes_a_disabling_rule() {
        // The property, not the formatting: a rule that switches an
        // output off is matched by whatever is plugged in when Hyprland
        // reads the file. Written while docked with the lid shut, then
        // read after undocking, it is the only display present — and
        // this file would be the thing that blanked it.
        let mut entry = enabled_entry();
        entry.enabled = false;
        let lua = generate(&[entry]);
        assert!(!lua.contains("hl.monitor("), "no rule at all may be emitted: {lua}");
        assert!(!lua.contains("disabled = true"), "got: {lua}");
    }

    #[test]
    fn a_disabled_output_is_still_named_so_the_file_explains_itself() {
        let mut entry = enabled_entry();
        entry.enabled = false;
        let lua = generate(&[entry]);
        // Every line it contributes must be a comment, or the point above
        // is lost the moment someone adds a field to the renderer.
        assert!(lua.contains("desc:BOE 0x0BC9"), "got: {lua}");
        for line in lua.lines().filter(|l| l.contains("desc:BOE 0x0BC9")) {
            assert!(line.trim_start().starts_with("--"), "not a comment: {line}");
        }
    }

    #[test]
    fn a_disabled_output_does_not_suppress_the_ones_that_are_on() {
        // The docked case end to end: the internal panel off, the
        // external carrying the session. The external's rule has to
        // survive the filtering.
        let mut internal = enabled_entry();
        internal.enabled = false;
        let mut external = enabled_entry();
        external.selector = "desc:GWD ARZOPA".to_string();
        let lua = generate(&[internal, external]);
        assert!(lua.contains("hl.monitor({ output = [[desc:GWD ARZOPA]]"), "got: {lua}");
        assert_eq!(lua.matches("hl.monitor(").count(), 1, "got: {lua}");
    }

    #[test]
    fn a_missing_mode_falls_back_to_preferred() {
        let mut entry = enabled_entry();
        entry.mode = None;
        let lua = generate(&[entry]);
        assert!(lua.contains("mode = [[preferred]]"), "got: {lua}");
    }

    #[test]
    fn every_transform_maps_to_hyprlands_own_numbering() {
        let cases = [
            (Transform::Normal, 0),
            (Transform::Rotate90, 1),
            (Transform::Rotate180, 2),
            (Transform::Rotate270, 3),
            (Transform::Flipped, 4),
            (Transform::Flipped90, 5),
            (Transform::Flipped180, 6),
            (Transform::Flipped270, 7),
        ];
        for (transform, expected) in cases {
            let mut entry = enabled_entry();
            entry.transform = transform;
            let lua = generate(&[entry]);
            assert!(
                lua.contains(&format!("transform = {expected} }}")),
                "transform {transform:?} should map to {expected}, got: {lua}"
            );
        }
    }

    #[test]
    fn a_fractional_refresh_rate_keeps_two_decimals() {
        let mut entry = enabled_entry();
        entry.mode = Some((1920, 1080, 59940));
        let lua = generate(&[entry]);
        assert!(lua.contains("1920x1080@59.94"), "got: {lua}");
    }

    #[test]
    fn a_connector_only_selector_needs_no_desc_prefix() {
        let mut entry = enabled_entry();
        entry.selector = "eDP-1".to_string();
        let lua = generate(&[entry]);
        assert!(lua.contains("output = [[eDP-1]]"), "got: {lua}");
    }

    #[test]
    fn multiple_entries_each_get_their_own_call() {
        let lua = generate(&[enabled_entry(), enabled_entry()]);
        assert_eq!(lua.matches("hl.monitor").count(), 2);
    }
}
