use crate::catalog::{self, CallShape};
use crate::lua::{lua_string, render_table, render_value};
use crate::model::{description_for, Action, Shortcut};

const HEADER: &str = "-- Generated by Hyprforge. Do not edit by hand — changes will be\n-- overwritten the next time a shortcut is saved in the Hyprforge Settings app.\n";

/// Renders `shortcuts` to a complete `keybinds.lua` body.
///
/// A shortcut missing either half — no key, or no dispatcher — is skipped
/// rather than emitted. `hl.bind` with an empty key would be a bind that can
/// never fire, and one with no dispatcher isn't valid Lua at all.
///
/// Disabled shortcuts are skipped too. `hl.window_rule` has an `enabled`
/// field so a rule can be present-but-off; `hl.bind` has no equivalent, so
/// "off" has to mean "not emitted".
pub fn generate(shortcuts: &[Shortcut]) -> String {
    let mut out = String::from(HEADER);
    out.push('\n');
    for shortcut in shortcuts {
        if !shortcut.enabled || shortcut.combo.is_empty() || shortcut.action.is_empty() {
            continue;
        }
        out.push_str(&render_one(shortcut));
    }
    out
}

/// One shortcut's `hl.bind` line, exactly as [`generate`] writes it.
///
/// Public so the editor can show the user the line their form is about to
/// produce — the same function, so a preview can't drift into being a
/// plausible-looking lie.
pub fn render_one(shortcut: &Shortcut) -> String {
    format!(
        "hl.bind({}, hl.dsp.{}({}), {})\n",
        lua_string(&shortcut.combo.to_bind_string()),
        shortcut.action.dispatcher.trim(),
        render_argument(&shortcut.action),
        render_options(shortcut),
    )
}

/// The text between the dispatcher's parentheses.
///
/// The shape comes from the catalog, not from guessing: a dispatcher that
/// takes a table gets `{ ... }` even when empty (Hyprland rejects
/// `hl.dsp.focus()` outright), one that takes a bare value gets the value
/// alone, and one that takes nothing gets nothing. An action the catalog
/// doesn't know falls back to its raw text — which is also how an action
/// stored before the catalog existed still renders.
///
/// Public for the editor's raw mode, which prefills its text box with the
/// argument the structured form would have produced. That prefill is what
/// the user then edits and saves, so it has to be this rule and not a
/// second copy of it.
pub fn render_argument(action: &Action) -> String {
    if let Some(raw) = &action.raw {
        return raw.trim().to_string();
    }
    match catalog::resolve(action).map(|entry| entry.shape) {
        Some(CallShape::None) => String::new(),
        Some(CallShape::Positional) => action
            .params
            .values()
            .next()
            .map(render_value)
            .unwrap_or_default(),
        // An unresolvable action with no raw text is still emitted as a
        // table rather than dropped: it came from somewhere (a hand-written
        // config, or a catalog entry removed since), and a table is the
        // shape almost every dispatcher wants.
        Some(CallShape::Table) | None => render_table(&action.params),
    }
}

/// `hl.bind`'s third argument: the description, plus whichever flags are on.
fn render_options(shortcut: &Shortcut) -> String {
    let mut entries = vec![("description", lua_string(&description_for(shortcut)))];
    for flag in shortcut.flags.set_flags() {
        entries.push((flag, "true".to_string()));
    }
    crate::lua::render_entries(&entries)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Action, BindFlags, KeyCombo, Modifier, ParamValue};
    use std::collections::BTreeMap;

    fn params(pairs: &[(&str, ParamValue)]) -> BTreeMap<String, ParamValue> {
        pairs.iter().map(|(k, v)| (k.to_string(), v.clone())).collect()
    }

    fn shortcut() -> Shortcut {
        Shortcut {
            name: "hyprforge-close-1".to_string(),
            enabled: true,
            combo: KeyCombo {
                mods: vec![Modifier::Super],
                key: "C".to_string(),
            },
            action: Action::with_params("window.close", BTreeMap::new()),
            description: "Close window".to_string(),
            flags: BindFlags::default(),
        }
    }

    #[test]
    fn generates_a_bind() {
        let lua = generate(&[shortcut()]);
        assert!(lua.contains("hl.bind([[SUPER + C]], hl.dsp.window.close({})"), "got: {lua}");
        assert!(lua.starts_with("-- Generated by Hyprforge"));
    }

    /// The bug this whole model change came out of: a dispatcher that takes
    /// a table has to *get* a table, or Hyprland rejects the entire file.
    #[test]
    fn a_table_dispatcher_gets_its_table() {
        let mut s = shortcut();
        s.action = Action::with_params(
            "focus",
            params(&[("direction", ParamValue::Str("left".into()))]),
        );
        let lua = generate(&[s]);
        assert!(lua.contains("hl.dsp.focus({ direction = [[left]] })"), "got: {lua}");
    }

    /// A positional dispatcher must *not* get a table.
    #[test]
    fn a_positional_dispatcher_gets_a_bare_value() {
        let mut s = shortcut();
        s.action =
            Action::with_params("exec_cmd", params(&[("cmd", ParamValue::Str("ghostty".into()))]));
        let lua = generate(&[s]);
        assert!(lua.contains("hl.dsp.exec_cmd([[ghostty]])"), "got: {lua}");
    }

    #[test]
    fn a_no_argument_dispatcher_gets_nothing() {
        let mut s = shortcut();
        s.action = Action::with_params("exit", BTreeMap::new());
        assert!(generate(&[s]).contains("hl.dsp.exit()"));
    }

    /// A workspace number must stay a number — `workspace = "3"` would mean
    /// a workspace *named* "3".
    #[test]
    fn a_numeric_workspace_is_not_quoted() {
        let mut s = shortcut();
        s.action = Action::with_params("focus", params(&[("workspace", ParamValue::Int(3))]));
        assert!(generate(&[s]).contains("hl.dsp.focus({ workspace = 3 })"));
    }

    #[test]
    fn set_flags_join_the_description_in_the_options_table() {
        let mut s = shortcut();
        s.flags = BindFlags { mouse: true, locked: true, ..BindFlags::default() };
        let lua = generate(&[s]);
        assert!(
            lua.contains("{ description = [[hyprforge: Close window]], mouse = true, locked = true }"),
            "got: {lua}"
        );
    }

    #[test]
    fn no_flags_means_just_a_description() {
        let lua = generate(&[shortcut()]);
        assert!(lua.contains("{ description = [[hyprforge: Close window]] })"), "got: {lua}");
    }

    /// Every generated bind carries the prefix, because that's how the app
    /// recognises its own binds in `hyprctl binds` later.
    #[test]
    fn every_bind_carries_a_prefixed_description() {
        let lua = generate(&[shortcut()]);
        assert!(lua.contains("description = [[hyprforge: Close window]]"), "got: {lua}");
    }

    /// The escape hatch, which is also what a store written before the
    /// catalog existed deserializes into — it has to keep generating exactly
    /// what it always did.
    #[test]
    fn a_raw_argument_is_emitted_verbatim() {
        let mut s = shortcut();
        s.action = Action::with_raw("exec_cmd", "[[ghostty]]");
        let lua = generate(&[s]);
        assert!(lua.contains("hl.dsp.exec_cmd([[ghostty]])"), "got: {lua}");
    }

    /// Raw wins outright — a half-migrated action must not emit both.
    #[test]
    fn raw_takes_precedence_over_params() {
        let mut s = shortcut();
        s.action = Action {
            dispatcher: "focus".to_string(),
            params: params(&[("direction", ParamValue::Str("left".into()))]),
            raw: Some("{ direction = [[right]] }".to_string()),
        };
        let lua = generate(&[s]);
        assert!(lua.contains("hl.dsp.focus({ direction = [[right]] })"), "got: {lua}");
        assert!(!lua.contains("left"));
    }

    /// `hl.bind` has no enabled flag, so off has to mean absent.
    #[test]
    fn a_disabled_shortcut_is_not_emitted() {
        let mut s = shortcut();
        s.enabled = false;
        assert!(!generate(&[s]).contains("hl.bind"));
    }

    #[test]
    fn a_shortcut_missing_its_key_or_action_is_skipped() {
        let mut no_key = shortcut();
        no_key.combo.key = "  ".to_string();
        assert!(!generate(&[no_key]).contains("hl.bind"));

        let mut no_action = shortcut();
        no_action.action.dispatcher = String::new();
        assert!(!generate(&[no_action]).contains("hl.bind"));
    }

    #[test]
    fn modifiers_render_in_a_stable_order() {
        let mut s = shortcut();
        s.combo.mods = vec![Modifier::Super, Modifier::Shift];
        let a = generate(&[s.clone()]);
        s.combo.mods = vec![Modifier::Shift, Modifier::Super];
        assert_eq!(a, generate(&[s]));
    }

    /// A command containing `]]` must not end the Lua string early.
    #[test]
    fn a_bracket_heavy_argument_stays_quoted() {
        let mut s = shortcut();
        s.action =
            Action::with_params("exec_cmd", params(&[("cmd", ParamValue::Str("echo ]]".into()))]));
        assert!(generate(&[s.clone()]).contains("[=[echo ]]]=]"));
        // The argument is passed through verbatim; the description is what
        // this crate quotes, and it must survive the same hazard.
        s.description = "weird ]] description".to_string();
        let lua = generate(&[s]);
        assert!(lua.contains("[=[hyprforge: weird ]] description]=]"), "got: {lua}");
    }

    #[test]
    fn a_keyless_shortcut_with_no_modifiers_still_binds() {
        let mut s = shortcut();
        s.combo.mods = vec![];
        s.combo.key = "XF86AudioPlay".to_string();
        assert!(generate(&[s]).contains("hl.bind([[XF86AudioPlay]]"));
    }
}
