use crate::model::{description_for, Shortcut};

const HEADER: &str = "-- Generated by Hyprforge. Do not edit by hand — changes will be\n-- overwritten the next time a shortcut is saved in the Hyprforge Settings app.\n";

/// Renders `shortcuts` to a complete `keybinds.lua` body.
///
/// A shortcut missing either half — no key, or no dispatcher — is skipped
/// rather than emitted. `hl.bind` with an empty key would be a bind that can
/// never fire, and one with no dispatcher isn't valid Lua at all.
///
/// Disabled shortcuts are skipped too. `hl.window_rule` has an `enabled`
/// field so a rule can be present-but-off; `hl.bind` has no equivalent, so
/// "off" has to mean "not emitted".
pub fn generate(shortcuts: &[Shortcut]) -> String {
    let mut out = String::from(HEADER);
    out.push('\n');
    for shortcut in shortcuts {
        if !shortcut.enabled || shortcut.combo.is_empty() || shortcut.action.is_empty() {
            continue;
        }
        out.push_str(&render(shortcut));
    }
    out
}

fn render(shortcut: &Shortcut) -> String {
    let dispatcher = shortcut.action.dispatcher.trim();
    let argument = shortcut.action.argument.trim();
    format!(
        "hl.bind({}, hl.dsp.{}({}), {{ description = {} }})\n",
        lua_string(&shortcut.combo.to_bind_string()),
        dispatcher,
        argument,
        lua_string(&description_for(shortcut)),
    )
}

/// Quotes with a Lua long bracket, which needs no escaping. Falls back a
/// level if the content itself contains `]]`.
fn lua_string(s: &str) -> String {
    if !s.contains("]]") {
        format!("[[{s}]]")
    } else {
        format!("[=[{s}]=]")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Action, KeyCombo, Modifier};

    fn shortcut() -> Shortcut {
        Shortcut {
            name: "hyprforge-close-1".to_string(),
            enabled: true,
            combo: KeyCombo {
                mods: vec![Modifier::Super],
                key: "C".to_string(),
            },
            action: Action {
                dispatcher: "window.close".to_string(),
                argument: String::new(),
            },
            description: "Close window".to_string(),
        }
    }

    #[test]
    fn generates_a_bind() {
        let lua = generate(&[shortcut()]);
        assert!(lua.contains("hl.bind([[SUPER + C]], hl.dsp.window.close()"), "got: {lua}");
        assert!(lua.starts_with("-- Generated by Hyprforge"));
    }

    /// Every generated bind carries the prefix, because that's how the app
    /// recognises its own binds in `hyprctl binds` later.
    #[test]
    fn every_bind_carries_a_prefixed_description() {
        let lua = generate(&[shortcut()]);
        assert!(lua.contains("description = [[hyprforge: Close window]]"), "got: {lua}");
    }

    #[test]
    fn an_argument_is_emitted_inside_the_call() {
        let mut s = shortcut();
        s.action = Action {
            dispatcher: "exec_cmd".to_string(),
            argument: "[[ghostty]]".to_string(),
        };
        let lua = generate(&[s]);
        assert!(lua.contains("hl.dsp.exec_cmd([[ghostty]])"), "got: {lua}");
    }

    /// `hl.bind` has no enabled flag, so off has to mean absent.
    #[test]
    fn a_disabled_shortcut_is_not_emitted() {
        let mut s = shortcut();
        s.enabled = false;
        assert!(!generate(&[s]).contains("hl.bind"));
    }

    #[test]
    fn a_shortcut_missing_its_key_or_action_is_skipped() {
        let mut no_key = shortcut();
        no_key.combo.key = "  ".to_string();
        assert!(!generate(&[no_key]).contains("hl.bind"));

        let mut no_action = shortcut();
        no_action.action.dispatcher = String::new();
        assert!(!generate(&[no_action]).contains("hl.bind"));
    }

    #[test]
    fn modifiers_render_in_a_stable_order() {
        let mut s = shortcut();
        s.combo.mods = vec![Modifier::Super, Modifier::Shift];
        let a = generate(&[s.clone()]);
        s.combo.mods = vec![Modifier::Shift, Modifier::Super];
        assert_eq!(a, generate(&[s]));
    }

    /// A command containing `]]` must not end the Lua string early.
    #[test]
    fn a_bracket_heavy_argument_stays_quoted() {
        let mut s = shortcut();
        s.action = Action {
            dispatcher: "exec_cmd".to_string(),
            argument: "[[sh -c 'echo ]]']]".to_string(),
        };
        // The argument is passed through verbatim; the description is what
        // this crate quotes, and it must survive the same hazard.
        s.description = "weird ]] description".to_string();
        let lua = generate(&[s]);
        assert!(lua.contains("[=[hyprforge: weird ]] description]=]"), "got: {lua}");
    }

    #[test]
    fn a_keyless_shortcut_with_no_modifiers_still_binds() {
        let mut s = shortcut();
        s.combo.mods = vec![];
        s.combo.key = "XF86AudioPlay".to_string();
        assert!(generate(&[s]).contains("hl.bind([[XF86AudioPlay]]"));
    }
}
