//! Converts a call recorded by `hyprforge-lua-import` (evaluating a user's
//! own `hyprland.lua`) back into this crate's own `KeyCombo`/`Action`.
//!
//! Takes plain `(kind, args)` rather than
//! `hyprforge_lua_import::RecordedCall` directly, so this crate never has
//! to depend on `hyprforge-lua-import` — and therefore never on `mlua` —
//! itself; only the caller orchestrating an import (the Settings GUI)
//! does. `serde_json::Value` is the shared currency instead.
//!
//! This recovers something `binds.rs`'s `hyprctl binds -j` read fundamentally
//! cannot: a real dispatcher path. `hyprctl` reports every Lua-defined
//! bind's dispatcher as opaque `__lua` — the *chord* is knowable that way,
//! the *action* never is. Evaluating the config for real, with `hl.dsp.*`
//! stubbed to record the path it was called through (see
//! `hyprforge-lua-import`'s dispatch proxy), is what makes the action
//! recoverable too.

use crate::model::{Action, KeyCombo, Modifier};
use serde_json::Value;

/// A shortcut's combo/action/description, recovered from a recorded
/// `hl.bind(combo, dispatch, opts)` call. `None` if the first argument
/// isn't a resolvable chord string — which a real interpreter always
/// produces even for `mainMod .. " + Q"`-style configs, so this only fails
/// for a call that genuinely isn't a normal bind.
///
/// `name`/`enabled` aren't part of the return: `name` is always freshly
/// generated by the caller via
/// [`generate_shortcut_name`](crate::model::generate_shortcut_name), and a
/// captured call has no "disabled" concept to recover — if `hl.bind` ran
/// at all, the bind was active.
pub fn shortcut_from_call(kind: &str, args: &[Value]) -> Option<(KeyCombo, Action, String)> {
    if kind != "bind" {
        return None;
    }
    let combo = parse_combo(args.first()?.as_str()?)?;
    let (dispatcher, argument) = args.get(1).and_then(dispatch_from_marker).unwrap_or_default();
    let description = args
        .get(2)
        .and_then(Value::as_object)
        .and_then(|t| t.get("description"))
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string();
    Some((combo, Action { dispatcher, argument }, description))
}

/// Inverse of [`KeyCombo::to_bind_string`]: splits on `+`, the last token
/// is the key, everything before it is a modifier keyword. Whitespace
/// around `+` is trimmed either way, so both `"SUPER + Q"` (this crate's
/// own rendering) and a hand-written `"SUPER+Q"` parse the same.
fn parse_combo(s: &str) -> Option<KeyCombo> {
    let parts: Vec<&str> = s.split('+').map(str::trim).filter(|p| !p.is_empty()).collect();
    let (key, mod_parts) = parts.split_last()?;
    if key.is_empty() {
        return None;
    }
    let mods: Vec<Modifier> = mod_parts.iter().filter_map(|p| modifier_from_keyword(p)).collect();
    Some(KeyCombo { mods, key: key.to_string() })
}

fn modifier_from_keyword(kw: &str) -> Option<Modifier> {
    Modifier::ALL.into_iter().find(|m| m.keyword().eq_ignore_ascii_case(kw))
}

/// Recovers `(dispatcher, argument)` from the marker table
/// `hyprforge-lua-import`'s `hl.dsp` proxy produces for a call like
/// `hl.dsp.window.close()` — `{ __hyprforge_dispatch = "window.close",
/// __hyprforge_args = {...} }`. `None` (via the caller's
/// `unwrap_or_default`) when the second argument isn't that shape at all
/// — e.g. a hand-written bind that calls something other than `hl.dsp.*`,
/// which this project has no way to recover the action for regardless of
/// approach.
fn dispatch_from_marker(v: &Value) -> Option<(String, String)> {
    let obj = v.as_object()?;
    let dispatcher = obj.get("__hyprforge_dispatch")?.as_str()?.to_string();
    let args: Vec<Value> = obj
        .get("__hyprforge_args")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let argument = args.iter().map(render_lua_literal).collect::<Vec<_>>().join(", ");
    Some((dispatcher, argument))
}

/// Renders a captured argument back to Lua source text — `Action::argument`
/// is spliced verbatim inside `hl.dsp.<dispatcher>(...)` by
/// [`crate::codegen::generate`], so a string has to come back already
/// quoted, the same long-bracket form this crate's own codegen uses.
fn render_lua_literal(v: &Value) -> String {
    match v {
        Value::String(s) => lua_string(s),
        Value::Number(n) => n.to_string(),
        Value::Bool(b) => b.to_string(),
        _ => String::new(),
    }
}

fn lua_string(s: &str) -> String {
    if !s.contains("]]") {
        format!("[[{s}]]")
    } else {
        format!("[=[{s}]=]")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Runs `lua_source` as `hyprland.lua` through the real sandboxed
    /// evaluator, in a throwaway directory.
    fn evaluated(lua_source: &str) -> hyprforge_lua_import::ImportResult {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("hyprland.lua"), lua_source).unwrap();
        let result = hyprforge_lua_import::evaluate(dir.path());
        assert!(result.failures.is_empty(), "unexpected failures: {:?}", result.failures);
        result
    }

    /// The case that motivates this whole feature: `hyprctl binds -j`
    /// could give us the resolved chord already, but never the dispatcher
    /// — this proves the Lua-VM approach recovers both.
    #[test]
    fn a_mod_key_variable_bind_recovers_both_chord_and_dispatcher() {
        let result = evaluated(
            r#"
            local mainMod = "SUPER"
            hl.bind(mainMod .. " + Q", hl.dsp.window.close(), { description = "Close window" })
            "#,
        );
        let call = &result.calls[0];
        let (combo, action, description) = shortcut_from_call(&call.kind, &call.args).unwrap();
        assert_eq!(combo.mods, vec![Modifier::Super]);
        assert_eq!(combo.key, "Q");
        assert_eq!(action.dispatcher, "window.close");
        assert_eq!(action.argument, "");
        assert_eq!(description, "Close window");
    }

    #[test]
    fn a_dispatcher_argument_round_trips_as_quoted_lua() {
        let result = evaluated(r#"hl.bind("SUPER + Return", hl.dsp.exec_cmd("ghostty"))"#);
        let (_, action, _) = shortcut_from_call(&result.calls[0].kind, &result.calls[0].args).unwrap();
        assert_eq!(action.dispatcher, "exec_cmd");
        assert_eq!(action.argument, "[[ghostty]]");
    }

    #[test]
    fn multiple_modifiers_all_parse_regardless_of_order() {
        let result = evaluated(r#"hl.bind("SUPER + SHIFT + Q", hl.dsp.window.close())"#);
        let (combo, _, _) = shortcut_from_call(&result.calls[0].kind, &result.calls[0].args).unwrap();
        assert_eq!(combo.mods, vec![Modifier::Super, Modifier::Shift]);
    }

    #[test]
    fn a_combo_with_no_modifiers_still_parses() {
        let result = evaluated(r#"hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl"))"#);
        let (combo, _, _) = shortcut_from_call(&result.calls[0].kind, &result.calls[0].args).unwrap();
        assert!(combo.mods.is_empty());
        assert_eq!(combo.key, "XF86AudioPlay");
    }

    #[test]
    fn a_missing_description_is_empty_not_a_failure() {
        let result = evaluated(r#"hl.bind("SUPER + Q", hl.dsp.window.close())"#);
        let (_, _, description) = shortcut_from_call(&result.calls[0].kind, &result.calls[0].args).unwrap();
        assert_eq!(description, "");
    }

    #[test]
    fn a_window_rule_call_is_not_mistaken_for_a_bind() {
        let result = evaluated(r#"hl.window_rule({ match = { class = "x" } })"#);
        assert!(shortcut_from_call(&result.calls[0].kind, &result.calls[0].args).is_none());
    }
}
