use hyprforge_windowrules::model::{Effects, Matcher, Opacity, Rule, Workspace, WorkspaceRule};
use hyprforge_windowrules::{codegen::generate, storage};

fn discord_rule() -> Rule {
    Rule {
        name: "hyprforge-discord-1".to_string(),
        enabled: true,
        matcher: Matcher {
            class: Some("discord".to_string()),
            ..Default::default()
        },
        effects: Effects {
            float: Some(true),
            ..Default::default()
        },
    }
}

#[test]
fn generates_basic_rule() {
    let lua = generate(&[discord_rule()], &[]);
    assert!(lua.contains("name = [[hyprforge-discord-1]]"));
    assert!(lua.contains("match = { class = [[discord]] }"));
    assert!(lua.contains("float = true"));
    assert!(lua.starts_with("-- Generated by Hyprforge"));
}

/// The rule this module went longest without: "Discord always opens on
/// workspace 3."
#[test]
fn generates_a_workspace_assignment() {
    let mut rule = discord_rule();
    rule.effects.workspace = Workspace { name: "3".to_string(), silent: false };
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("workspace = [[3]]"), "got: {lua}");
}

/// `silent` is a suffix inside Hyprland's one string, not a field of its
/// own — the user shouldn't have to know that to get it.
#[test]
fn silent_is_emitted_as_a_suffix_not_a_field() {
    let mut rule = discord_rule();
    rule.effects.workspace = Workspace { name: "name:coding".to_string(), silent: true };
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("workspace = [[name:coding silent]]"), "got: {lua}");
    assert!(!lua.contains("silent = true"), "silent is not its own field");
}

/// `unset` is a keyword rather than a workspace, so suffixing it would make
/// a value Hyprland doesn't recognise.
#[test]
fn unset_never_takes_the_silent_suffix() {
    let mut rule = discord_rule();
    rule.effects.workspace = Workspace { name: "unset".to_string(), silent: true };
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("workspace = [[unset]]"), "got: {lua}");
}

#[test]
fn an_unset_workspace_emits_no_field_at_all() {
    let lua = generate(&[discord_rule()], &[]);
    assert!(!lua.contains("workspace"), "got: {lua}");
}

/// Whitespace around a typed workspace name must not reach the Lua, or the
/// suffix ends up doubled up with it.
#[test]
fn a_workspace_name_is_trimmed() {
    let mut rule = discord_rule();
    rule.effects.workspace = Workspace { name: "  3  ".to_string(), silent: true };
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("workspace = [[3 silent]]"), "got: {lua}");
}

#[test]
fn generates_tag_as_both_a_matcher_and_an_effect() {
    let mut rule = discord_rule();
    rule.matcher.tag = Some("term".to_string());
    rule.effects.tag = Some("+code".to_string());
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("tag = [[term]]"), "matcher tag missing: {lua}");
    assert!(lua.contains("tag = [[+code]]"), "effect tag missing: {lua}");
}

/// Hyprland has no `floating` match property — it's `float`, same as the
/// effect. Emitting the wrong one aborts the whole file with "unknown match
/// property", so every other rule in it stops working too. Caught by
/// `tests/live_lua.rs` against a real compositor; pinned here so it can't
/// come back without a live run.
#[test]
fn the_floating_matcher_is_emitted_as_float() {
    let mut rule = discord_rule();
    rule.matcher.floating = Some(false);
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("float = false"), "got: {lua}");
    assert!(!lua.contains("floating"), "there is no `floating` match property: {lua}");
}

#[test]
fn generates_a_content_matcher() {
    let mut rule = discord_rule();
    rule.matcher.content = Some("game".to_string());
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("content = [[game]]"), "got: {lua}");
}

#[test]
fn skips_empty_matcher() {
    let rule = Rule {
        name: "hyprforge-empty-1".to_string(),
        enabled: true,
        matcher: Matcher::default(),
        effects: Effects::default(),
    };
    let lua = generate(&[rule], &[]);
    assert!(!lua.contains("hyprforge-empty-1"));
}

#[test]
fn preserves_order() {
    let mut a = discord_rule();
    a.name = "hyprforge-a-1".to_string();
    let mut b = discord_rule();
    b.name = "hyprforge-b-1".to_string();

    let lua = generate(&[a, b], &[]);
    let pos_a = lua.find("hyprforge-a-1").unwrap();
    let pos_b = lua.find("hyprforge-b-1").unwrap();
    assert!(pos_a < pos_b);
}

#[test]
fn opacity_override_serializes_with_suffix() {
    let rule = Rule {
        name: "hyprforge-kitty-1".to_string(),
        enabled: true,
        matcher: Matcher {
            class: Some("kitty".to_string()),
            ..Default::default()
        },
        effects: Effects {
            opacity: Opacity {
                active: Some(0.8),
                inactive: Some(0.8),
                fullscreen: Some(1.0),
                is_override: true,
            },
            ..Default::default()
        },
    };
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("opacity = [[0.8 override 0.8 override 1 override]]"));
}

#[test]
fn regex_strings_pass_through_verbatim() {
    let rule = Rule {
        name: "hyprforge-regexy-1".to_string(),
        enabled: true,
        matcher: Matcher {
            title: Some(r"^(foo|bar)\.exe$".to_string()),
            ..Default::default()
        },
        effects: Effects::default(),
    };
    let lua = generate(&[rule], &[]);
    assert!(lua.contains(r"title = [[^(foo|bar)\.exe$]]"));
}

#[test]
fn move_expression_vs_literal() {
    let rule = Rule {
        name: "hyprforge-move-1".to_string(),
        enabled: true,
        matcher: Matcher {
            class: Some("x".to_string()),
            ..Default::default()
        },
        effects: Effects {
            r#move: Some([
                "100".to_string(),
                "cursor_y-(window_h*0.5)".to_string(),
            ]),
            ..Default::default()
        },
    };
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("move = { 100, [[cursor_y-(window_h*0.5)]] }"));
}

#[test]
fn toml_round_trip_preserves_order_and_fields() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("window-rules.toml");

    let rules = vec![discord_rule(), {
        let mut r = discord_rule();
        r.name = "hyprforge-slack-1".to_string();
        r.matcher.class = Some("slack".to_string());
        r.effects.rounding = Some(8);
        r
    }];

    let stored = storage::Rules { rules: rules.clone(), workspace_rules: Vec::new() };
    storage::save(&path, &stored).unwrap();
    let loaded = storage::load(&path).unwrap();
    assert_eq!(loaded.rules, rules);
}

#[test]
fn load_missing_file_is_empty_not_error() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("nope.toml");
    let rules = storage::load(&path).unwrap();
    assert!(rules.rules.is_empty());
    assert!(rules.workspace_rules.is_empty());
}

/// "Steam on the external display", the thing window rules alone can't say.
#[test]
fn generates_a_workspace_to_monitor_pin() {
    let wr = WorkspaceRule {
        workspace: "name:gaming".to_string(),
        monitor: "desc:GWD ARZOPA".to_string(),
        default: true,
        persistent: false,
    };
    let lua = generate(&[], &[wr]);
    assert!(
        lua.contains("hl.workspace_rule({ workspace = [[name:gaming]], monitor = [[desc:GWD ARZOPA]], default = true })"),
        "got: {lua}"
    );
}

/// A pin with no monitor is "no opinion about where this lives". Emitting
/// `monitor = [[]]` would instead ask Hyprland to find a monitor named "".
#[test]
fn a_blank_monitor_emits_no_monitor_field() {
    let wr = WorkspaceRule { workspace: "3".to_string(), ..Default::default() };
    let lua = generate(&[], &[wr]);
    assert!(lua.contains("hl.workspace_rule({ workspace = [[3]] })"), "got: {lua}");
    assert!(!lua.contains("monitor"), "got: {lua}");
}

#[test]
fn a_workspace_rule_naming_no_workspace_is_skipped() {
    let wr = WorkspaceRule { monitor: "desc:X".to_string(), ..Default::default() };
    let lua = generate(&[], &[wr]);
    assert!(!lua.contains("workspace_rule"), "got: {lua}");
}

/// Workspace rules lead, so the file reads as "where workspaces live, then
/// what windows do".
#[test]
fn workspace_rules_are_emitted_before_window_rules() {
    let wr = WorkspaceRule { workspace: "3".to_string(), ..Default::default() };
    let lua = generate(&[discord_rule()], &[wr]);
    assert!(lua.find("workspace_rule").unwrap() < lua.find("window_rule").unwrap());
}

#[test]
fn both_rule_kinds_round_trip_through_one_toml() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("window-rules.toml");
    let stored = storage::Rules {
        rules: vec![discord_rule()],
        workspace_rules: vec![WorkspaceRule {
            workspace: "name:gaming".to_string(),
            monitor: "desc:GWD ARZOPA".to_string(),
            default: true,
            persistent: true,
        }],
    };
    storage::save(&path, &stored).unwrap();
    assert_eq!(storage::load(&path).unwrap(), stored);
}

/// A TOML written before workspace rules existed must still load.
#[test]
fn a_file_without_workspace_rules_still_loads() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("old.toml");
    std::fs::write(
        &path,
        "[[rule]]\nname = \"hyprforge-old-1\"\nenabled = true\n\n[rule.matcher]\nclass = \"old\"\n",
    )
    .unwrap();
    let loaded = storage::load(&path).unwrap();
    assert_eq!(loaded.rules.len(), 1);
    assert!(loaded.workspace_rules.is_empty());
}
