use hyprforge_windowrules::model::{
    Effects, LayerRule, Matcher, Opacity, Rule, Workspace, WorkspaceRule,
};
use hyprforge_windowrules::{codegen::generate, codegen::generate_all, storage};

fn discord_rule() -> Rule {
    Rule {
        name: "hyprforge-discord-1".to_string(),
        enabled: true,
        matcher: Matcher {
            class: Some("discord".to_string()),
            ..Default::default()
        },
        effects: Effects {
            float: Some(true),
            ..Default::default()
        },
    }
}

#[test]
fn generates_basic_rule() {
    let lua = generate(&[discord_rule()], &[]);
    assert!(lua.contains("name = [[hyprforge-discord-1]]"));
    assert!(lua.contains("match = { class = [[discord]] }"));
    assert!(lua.contains("float = true"));
    assert!(lua.starts_with("-- Generated by Hyprforge"));
}

/// The rule this module went longest without: "Discord always opens on
/// workspace 3."
#[test]
fn generates_a_workspace_assignment() {
    let mut rule = discord_rule();
    rule.effects.workspace = Workspace { name: "3".to_string(), silent: false };
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("workspace = [[3]]"), "got: {lua}");
}

/// `silent` is a suffix inside Hyprland's one string, not a field of its
/// own — the user shouldn't have to know that to get it.
#[test]
fn silent_is_emitted_as_a_suffix_not_a_field() {
    let mut rule = discord_rule();
    rule.effects.workspace = Workspace { name: "name:coding".to_string(), silent: true };
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("workspace = [[name:coding silent]]"), "got: {lua}");
    assert!(!lua.contains("silent = true"), "silent is not its own field");
}

/// `unset` is a keyword rather than a workspace, so suffixing it would make
/// a value Hyprland doesn't recognise.
#[test]
fn unset_never_takes_the_silent_suffix() {
    let mut rule = discord_rule();
    rule.effects.workspace = Workspace { name: "unset".to_string(), silent: true };
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("workspace = [[unset]]"), "got: {lua}");
}

#[test]
fn an_unset_workspace_emits_no_field_at_all() {
    let lua = generate(&[discord_rule()], &[]);
    assert!(!lua.contains("workspace"), "got: {lua}");
}

/// Whitespace around a typed workspace name must not reach the Lua, or the
/// suffix ends up doubled up with it.
#[test]
fn a_workspace_name_is_trimmed() {
    let mut rule = discord_rule();
    rule.effects.workspace = Workspace { name: "  3  ".to_string(), silent: true };
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("workspace = [[3 silent]]"), "got: {lua}");
}

#[test]
fn generates_tag_as_both_a_matcher_and_an_effect() {
    let mut rule = discord_rule();
    rule.matcher.tag = Some("term".to_string());
    rule.effects.tag = Some("+code".to_string());
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("tag = [[term]]"), "matcher tag missing: {lua}");
    assert!(lua.contains("tag = [[+code]]"), "effect tag missing: {lua}");
}

/// Hyprland has no `floating` match property — it's `float`, same as the
/// effect. Emitting the wrong one aborts the whole file with "unknown match
/// property", so every other rule in it stops working too. Caught by
/// `tests/live_lua.rs` against a real compositor; pinned here so it can't
/// come back without a live run.
#[test]
fn the_floating_matcher_is_emitted_as_float() {
    let mut rule = discord_rule();
    rule.matcher.floating = Some(false);
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("float = false"), "got: {lua}");
    assert!(!lua.contains("floating"), "there is no `floating` match property: {lua}");
}

#[test]
fn generates_a_content_matcher() {
    let mut rule = discord_rule();
    rule.matcher.content = Some("game".to_string());
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("content = [[game]]"), "got: {lua}");
}

/// Every boolean effect, spelled as Hyprland spells it. Names confirmed
/// against a running 0.56.1 before being generated; `tests/live_lua.rs`
/// re-checks them.
#[test]
fn generates_the_boolean_effects() {
    let mut rule = discord_rule();
    rule.effects.opaque = Some(true);
    rule.effects.no_anim = Some(true);
    rule.effects.no_focus = Some(true);
    rule.effects.stay_focused = Some(true);
    rule.effects.dim_around = Some(true);
    rule.effects.keep_aspect_ratio = Some(true);
    let lua = generate(&[rule], &[]);
    for expected in [
        "opaque = true",
        "no_anim = true",
        "no_focus = true",
        "stay_focused = true",
        "dim_around = true",
        "keep_aspect_ratio = true",
    ] {
        assert!(lua.contains(expected), "missing {expected}: {lua}");
    }
}

/// Hyprland has no `no_border` effect; zero here is how that gets said, so
/// it must survive rather than being treated as "unset".
#[test]
fn a_border_size_of_zero_is_emitted() {
    let mut rule = discord_rule();
    rule.effects.border_size = Some(0);
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("border_size = 0"), "got: {lua}");
}

/// Unlike move/size these take no expressions, so they're emitted bare.
#[test]
fn min_and_max_size_are_plain_integer_pairs() {
    let mut rule = discord_rule();
    rule.effects.min_size = Some([200, 150]);
    rule.effects.max_size = Some([800, 600]);
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("min_size = { 200, 150 }"), "got: {lua}");
    assert!(lua.contains("max_size = { 800, 600 }"), "got: {lua}");
}

/// An animation may carry a percentage, so it's a quoted string rather than
/// a bare token.
#[test]
fn an_animation_keeps_its_style_argument() {
    let mut rule = discord_rule();
    rule.effects.animation = Some("popin 80%".to_string());
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("animation = [[popin 80%]]"), "got: {lua}");
}

/// Only these four are accepted; Hyprland rejects anything else outright,
/// and a rejected field aborts the whole file.
#[test]
fn every_idle_inhibit_mode_is_one_hyprland_accepts() {
    for mode in hyprforge_windowrules::model::IDLE_INHIBIT_MODES {
        let mut rule = discord_rule();
        rule.effects.idle_inhibit = Some(mode.to_string());
        let lua = generate(&[rule], &[]);
        assert!(lua.contains(&format!("idle_inhibit = [[{mode}]]")), "got: {lua}");
    }
}

/// The static effects — how a window comes up, rather than how it behaves
/// once it's up. Names probed against a running 0.56.1; the wiki page this
/// project otherwise relies on documents the dynamic table only.
#[test]
fn generates_the_static_effects() {
    let mut rule = discord_rule();
    rule.effects.tile = Some(true);
    rule.effects.fullscreen = Some(true);
    rule.effects.maximize = Some(true);
    rule.effects.pin = Some(true);
    rule.effects.center = Some(true);
    rule.effects.no_initial_focus = Some(true);
    rule.effects.no_close_for = Some(5);
    let lua = generate(&[rule], &[]);
    for expected in [
        "tile = true",
        "fullscreen = true",
        "maximize = true",
        "pin = true",
        "center = true",
        "no_initial_focus = true",
        "no_close_for = 5",
    ] {
        assert!(lua.contains(expected), "missing {expected}: {lua}");
    }
}

/// Per-window monitor assignment, stored the same way a workspace pin stores
/// it — by description, so it survives a replug.
#[test]
fn a_window_can_be_sent_to_a_monitor_by_description() {
    let mut rule = discord_rule();
    rule.effects.monitor = Some("desc:GWD ARZOPA".to_string());
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("monitor = [[desc:GWD ARZOPA]]"), "got: {lua}");
}

/// Hyprland accepts any string for these two and silently does nothing with
/// one it doesn't know, so the generator must pass them through untouched
/// rather than "helpfully" normalising a value it can't validate either.
#[test]
fn unvalidated_string_effects_pass_through_verbatim() {
    let mut rule = discord_rule();
    rule.effects.suppress_event = Some("maximizefullscreen".to_string());
    rule.effects.group = Some("barred".to_string());
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("suppress_event = [[maximizefullscreen]]"), "got: {lua}");
    assert!(lua.contains("group = [[barred]]"), "got: {lua}");
}

/// The lists offered in the UI are a convenience, not a constraint — but
/// they still have to be values the compositor acts on.
#[test]
fn the_offered_suppress_and_group_values_are_the_documented_ones() {
    use hyprforge_windowrules::model::{GROUP_MODES, SUPPRESS_EVENTS};
    assert!(SUPPRESS_EVENTS.contains(&"fullscreen"));
    assert!(SUPPRESS_EVENTS.contains(&"activatefocus"));
    assert!(GROUP_MODES.contains(&"new"));
    assert!(GROUP_MODES.contains(&"deny"));
}

#[test]
fn unset_effects_emit_nothing() {
    let lua = generate(&[discord_rule()], &[]);
    for absent in ["opaque", "no_anim", "stay_focused", "border_size", "min_size", "idle_inhibit"] {
        assert!(!lua.contains(absent), "{absent} should not appear: {lua}");
    }
}

#[test]
fn skips_empty_matcher() {
    let rule = Rule {
        name: "hyprforge-empty-1".to_string(),
        enabled: true,
        matcher: Matcher::default(),
        effects: Effects::default(),
    };
    let lua = generate(&[rule], &[]);
    assert!(!lua.contains("hyprforge-empty-1"));
}

#[test]
fn preserves_order() {
    let mut a = discord_rule();
    a.name = "hyprforge-a-1".to_string();
    let mut b = discord_rule();
    b.name = "hyprforge-b-1".to_string();

    let lua = generate(&[a, b], &[]);
    let pos_a = lua.find("hyprforge-a-1").unwrap();
    let pos_b = lua.find("hyprforge-b-1").unwrap();
    assert!(pos_a < pos_b);
}

#[test]
fn opacity_override_serializes_with_suffix() {
    let rule = Rule {
        name: "hyprforge-kitty-1".to_string(),
        enabled: true,
        matcher: Matcher {
            class: Some("kitty".to_string()),
            ..Default::default()
        },
        effects: Effects {
            opacity: Opacity {
                active: Some(0.8),
                inactive: Some(0.8),
                fullscreen: Some(1.0),
                is_override: true,
            },
            ..Default::default()
        },
    };
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("opacity = [[0.8 override 0.8 override 1 override]]"));
}

#[test]
fn regex_strings_pass_through_verbatim() {
    let rule = Rule {
        name: "hyprforge-regexy-1".to_string(),
        enabled: true,
        matcher: Matcher {
            title: Some(r"^(foo|bar)\.exe$".to_string()),
            ..Default::default()
        },
        effects: Effects::default(),
    };
    let lua = generate(&[rule], &[]);
    assert!(lua.contains(r"title = [[^(foo|bar)\.exe$]]"));
}

#[test]
fn move_expression_vs_literal() {
    let rule = Rule {
        name: "hyprforge-move-1".to_string(),
        enabled: true,
        matcher: Matcher {
            class: Some("x".to_string()),
            ..Default::default()
        },
        effects: Effects {
            r#move: Some([
                "100".to_string(),
                "cursor_y-(window_h*0.5)".to_string(),
            ]),
            ..Default::default()
        },
    };
    let lua = generate(&[rule], &[]);
    assert!(lua.contains("move = { 100, [[cursor_y-(window_h*0.5)]] }"));
}

#[test]
fn toml_round_trip_preserves_order_and_fields() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("window-rules.toml");

    let rules = vec![discord_rule(), {
        let mut r = discord_rule();
        r.name = "hyprforge-slack-1".to_string();
        r.matcher.class = Some("slack".to_string());
        r.effects.rounding = Some(8);
        r
    }];

    let stored = storage::Rules { rules: rules.clone(), ..Default::default() };
    storage::save(&path, &stored).unwrap();
    let loaded = storage::load(&path).unwrap();
    assert_eq!(loaded.rules, rules);
}

#[test]
fn load_missing_file_is_empty_not_error() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("nope.toml");
    let rules = storage::load(&path).unwrap();
    assert!(rules.rules.is_empty());
    assert!(rules.workspace_rules.is_empty());
}

/// "Steam on the external display", the thing window rules alone can't say.
#[test]
fn generates_a_workspace_to_monitor_pin() {
    let wr = WorkspaceRule {
        workspace: "name:gaming".to_string(),
        monitor: "desc:GWD ARZOPA".to_string(),
        default: true,
        persistent: false,
    };
    let lua = generate(&[], &[wr]);
    assert!(
        lua.contains("hl.workspace_rule({ workspace = [[name:gaming]], monitor = [[desc:GWD ARZOPA]], default = true })"),
        "got: {lua}"
    );
}

/// A pin with no monitor is "no opinion about where this lives". Emitting
/// `monitor = [[]]` would instead ask Hyprland to find a monitor named "".
#[test]
fn a_blank_monitor_emits_no_monitor_field() {
    let wr = WorkspaceRule { workspace: "3".to_string(), ..Default::default() };
    let lua = generate(&[], &[wr]);
    assert!(lua.contains("hl.workspace_rule({ workspace = [[3]] })"), "got: {lua}");
    assert!(!lua.contains("monitor"), "got: {lua}");
}

#[test]
fn a_workspace_rule_naming_no_workspace_is_skipped() {
    let wr = WorkspaceRule { monitor: "desc:X".to_string(), ..Default::default() };
    let lua = generate(&[], &[wr]);
    assert!(!lua.contains("workspace_rule"), "got: {lua}");
}

/// Workspace rules lead, so the file reads as "where workspaces live, then
/// what windows do".
#[test]
fn workspace_rules_are_emitted_before_window_rules() {
    let wr = WorkspaceRule { workspace: "3".to_string(), ..Default::default() };
    let lua = generate(&[discord_rule()], &[wr]);
    assert!(lua.find("workspace_rule").unwrap() < lua.find("window_rule").unwrap());
}

#[test]
fn both_rule_kinds_round_trip_through_one_toml() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("window-rules.toml");
    let stored = storage::Rules {
        rules: vec![discord_rule()],
        workspace_rules: vec![WorkspaceRule {
            workspace: "name:gaming".to_string(),
            monitor: "desc:GWD ARZOPA".to_string(),
            default: true,
            persistent: true,
        }],
        ..Default::default()
    };
    storage::save(&path, &stored).unwrap();
    assert_eq!(storage::load(&path).unwrap(), stored);
}

/// A TOML written before workspace rules existed must still load.
#[test]
fn a_file_without_workspace_rules_still_loads() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("old.toml");
    std::fs::write(
        &path,
        "[[rule]]\nname = \"hyprforge-old-1\"\nenabled = true\n\n[rule.matcher]\nclass = \"old\"\n",
    )
    .unwrap();
    let loaded = storage::load(&path).unwrap();
    assert_eq!(loaded.rules.len(), 1);
    assert!(loaded.workspace_rules.is_empty());
}

fn notif_blur() -> LayerRule {
    LayerRule {
        name: "hyprforge-notif-blur".to_string(),
        enabled: true,
        namespace: "^notif$".to_string(),
        blur: Some(true),
    }
}

/// The exact shape a live Hyprland 0.56 accepted. A field beyond these
/// three rejects the whole file, window rules and all.
#[test]
fn a_layer_rule_renders_as_the_lua_form_hyprland_accepts() {
    let stored = storage::Rules { layer_rules: vec![notif_blur()], ..Default::default() };
    let lua = generate_all(&stored);
    assert!(
        lua.contains(
            "hl.layer_rule({ name = [[hyprforge-notif-blur]], match = { namespace = [[^notif$]] }, blur = true })"
        ),
        "got: {lua}"
    );
}

/// Whether `hl.layer_rule` takes `enabled` is unverified, and an unknown
/// field fails the file, so a disabled rule is simply not written.
#[test]
fn a_disabled_layer_rule_is_not_emitted() {
    let mut rule = notif_blur();
    rule.enabled = false;
    let stored = storage::Rules { layer_rules: vec![rule], ..Default::default() };
    assert!(!generate_all(&stored).contains("hl.layer_rule"));
}

/// Window rules come first and layer rules after, in one file.
#[test]
fn generate_all_keeps_everything_generate_writes() {
    let stored = storage::Rules {
        rules: vec![discord_rule()],
        layer_rules: vec![notif_blur()],
        ..Default::default()
    };
    let all = generate_all(&stored);
    assert!(all.starts_with(&generate(&stored.rules, &stored.workspace_rules)), "got: {all}");
    assert!(all.find("hl.window_rule") < all.find("hl.layer_rule"), "got: {all}");
}

/// Layer rules are written by Setup, not the Window Rules page — they have
/// to survive a load and save, or that page's next save deletes them.
#[test]
fn layer_rules_round_trip_through_the_toml() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("window-rules.toml");
    let stored = storage::Rules {
        rules: vec![discord_rule()],
        layer_rules: vec![notif_blur()],
        ..Default::default()
    };
    storage::save(&path, &stored).unwrap();
    assert_eq!(storage::load(&path).unwrap(), stored);
}

/// A file with no layer rules is written exactly as it was before they
/// existed — no empty `layer_rule` key appears in anybody's TOML.
#[test]
fn no_layer_rules_leaves_the_toml_unchanged() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("window-rules.toml");
    let stored = storage::Rules { rules: vec![discord_rule()], ..Default::default() };
    storage::save(&path, &stored).unwrap();
    assert!(!std::fs::read_to_string(&path).unwrap().contains("layer_rule"));
}
