use crate::model::{Rule, WorkspaceRule};

const HEADER: &str = "-- Generated by Hyprforge. Do not edit by hand — changes will be\n-- overwritten the next time a rule is saved in the Hyprforge Settings app.\n";

/// Renders both rule kinds to a complete `window-rules.lua` body.
///
/// Window rules keep TOML array order, which is semantically meaningful —
/// later rules override earlier ones for the same window. Rules with an empty
/// matcher are skipped rather than emitted, since Hyprland requires at least
/// one match field.
///
/// Workspace rules are emitted first. Their order carries no meaning to
/// Hyprland (they key off distinct workspaces), so this is purely so the file
/// reads as "where workspaces live, then what windows do".
pub fn generate(rules: &[Rule], workspace_rules: &[WorkspaceRule]) -> String {
    let mut out = String::from(HEADER);
    out.push('\n');
    for wr in workspace_rules {
        if wr.is_empty() {
            continue;
        }
        out.push_str(&render_workspace_rule(wr));
        out.push('\n');
    }
    for rule in rules {
        if rule.matcher.is_empty() {
            continue;
        }
        out.push_str(&render_one(rule));
        out.push('\n');
    }
    out
}

fn render_workspace_rule(wr: &WorkspaceRule) -> String {
    let mut fields = vec![format!("workspace = {}", lua_string(wr.workspace.trim()))];
    // A blank monitor means "no opinion about where this lives" — emitting
    // an empty string would instead ask Hyprland to find a monitor named "".
    if !wr.monitor.trim().is_empty() {
        fields.push(format!("monitor = {}", lua_string(wr.monitor.trim())));
    }
    if wr.default {
        fields.push("default = true".to_string());
    }
    if wr.persistent {
        fields.push("persistent = true".to_string());
    }
    format!("hl.workspace_rule({{ {} }})\n", fields.join(", "))
}

/// One rule's `hl.window_rule` line, exactly as [`generate`] writes it.
///
/// Public so the editor can show the user the line their form is about to
/// produce — the same function, so a preview can't drift into being a
/// plausible-looking lie.
pub fn render_one(rule: &Rule) -> String {
    let mut fields = Vec::new();
    fields.push(format!("name = {}", lua_string(&rule.name)));
    fields.push(format!("enabled = {}", rule.enabled));
    fields.push(format!("match = {}", render_matcher(&rule.matcher)));

    let e = &rule.effects;
    if !e.workspace.is_empty() {
        fields.push(format!(
            "workspace = {}",
            lua_string(&e.workspace.to_lua_value())
        ));
    }
    if let Some(v) = &e.tag {
        fields.push(format!("tag = {}", lua_string(v)));
    }
    if let Some(v) = e.float {
        fields.push(format!("float = {v}"));
    }
    if let Some([x, y]) = &e.r#move {
        fields.push(format!("move = {{ {}, {} }}", lua_expr(x), lua_expr(y)));
    }
    if let Some([w, h]) = &e.size {
        fields.push(format!("size = {{ {}, {} }}", lua_expr(w), lua_expr(h)));
    }
    if !e.opacity.is_empty() {
        fields.push(format!("opacity = {}", lua_string(&e.opacity.to_lua_value())));
    }
    if let Some(color) = &e.border_color {
        fields.push(format!("border_color = {}", lua_string(color)));
    }
    if let Some(v) = e.no_blur {
        fields.push(format!("no_blur = {v}"));
    }
    if let Some(v) = e.rounding {
        fields.push(format!("rounding = {v}"));
    }
    for (name, value) in [
        ("opaque", e.opaque),
        ("no_anim", e.no_anim),
        ("no_focus", e.no_focus),
        ("stay_focused", e.stay_focused),
        ("dim_around", e.dim_around),
        ("keep_aspect_ratio", e.keep_aspect_ratio),
    ] {
        if let Some(v) = value {
            fields.push(format!("{name} = {v}"));
        }
    }
    if let Some(v) = e.border_size {
        fields.push(format!("border_size = {v}"));
    }
    // Plain integers, not expressions — unlike `move`/`size`, these two take
    // no `monitor_w * 0.5` form, so there's nothing to quote.
    if let Some([w, h]) = e.min_size {
        fields.push(format!("min_size = {{ {w}, {h} }}"));
    }
    if let Some([w, h]) = e.max_size {
        fields.push(format!("max_size = {{ {w}, {h} }}"));
    }
    if let Some(v) = &e.animation {
        fields.push(format!("animation = {}", lua_string(v)));
    }
    if let Some(v) = &e.idle_inhibit {
        fields.push(format!("idle_inhibit = {}", lua_string(v)));
    }
    for (name, value) in [
        ("tile", e.tile),
        ("fullscreen", e.fullscreen),
        ("maximize", e.maximize),
        ("pin", e.pin),
        ("center", e.center),
        ("no_initial_focus", e.no_initial_focus),
    ] {
        if let Some(v) = value {
            fields.push(format!("{name} = {v}"));
        }
    }
    if let Some(v) = &e.monitor {
        fields.push(format!("monitor = {}", lua_string(v)));
    }
    if let Some(v) = &e.suppress_event {
        fields.push(format!("suppress_event = {}", lua_string(v)));
    }
    if let Some(v) = &e.group {
        fields.push(format!("group = {}", lua_string(v)));
    }
    if let Some(v) = e.no_close_for {
        fields.push(format!("no_close_for = {v}"));
    }

    format!("hl.window_rule({{ {} }})\n", fields.join(", "))
}

fn render_matcher(m: &crate::model::Matcher) -> String {
    let mut parts = Vec::new();
    if let Some(v) = &m.class {
        parts.push(format!("class = {}", lua_string(v)));
    }
    if let Some(v) = &m.title {
        parts.push(format!("title = {}", lua_string(v)));
    }
    if let Some(v) = &m.initial_class {
        parts.push(format!("initial_class = {}", lua_string(v)));
    }
    if let Some(v) = &m.initial_title {
        parts.push(format!("initial_title = {}", lua_string(v)));
    }
    if let Some(v) = m.fullscreen {
        parts.push(format!("fullscreen = {v}"));
    }
    if let Some(v) = m.floating {
        // Hyprland spells the *matcher* `float`, same as the effect — there
        // is no `floating` match property, and emitting one aborts the whole
        // file with "unknown match property", taking every other rule in it
        // down too. The model keeps `floating` because that's the TOML key
        // users may already have written, and because `Effects::float` next
        // to a `Matcher::float` would read as the same thing.
        parts.push(format!("float = {v}"));
    }
    if let Some(v) = m.xwayland {
        parts.push(format!("xwayland = {v}"));
    }
    if let Some(v) = &m.tag {
        parts.push(format!("tag = {}", lua_string(v)));
    }
    if let Some(v) = &m.content {
        parts.push(format!("content = {}", lua_string(v)));
    }
    format!("{{ {} }}", parts.join(", "))
}

/// A literal numeric/pixel expression is emitted bare; anything else
/// (Hyprland move/size expression strings like `"cursor_x-(window_w*0.5)"`)
/// is quoted.
fn lua_expr(s: &str) -> String {
    if s.parse::<f64>().is_ok() {
        s.to_string()
    } else {
        lua_string(s)
    }
}

/// Quotes using a Lua long-bracket string, which needs no escaping and so
/// passes RE2 regex strings through verbatim.
///
/// Shared rather than reimplemented: this crate's own copy tested only for
/// `]]` in the content, which let a perfectly ordinary class pattern like
/// `^firefox[0-9]` close its string a character early and take the whole
/// generated file down. See [`hyprforge_core::lua`].
use hyprforge_core::lua::lua_string;
