use crate::model::Rule;

const HEADER: &str = "-- Generated by Hyprforge. Do not edit by hand — changes will be\n-- overwritten the next time a rule is saved in the Hyprforge Settings app.\n";

/// Renders `rules` to a complete `window-rules.lua` body, in TOML array
/// order (order is semantically meaningful — later rules override earlier
/// ones for the same window). Rules with an empty matcher are skipped
/// rather than emitted, since Hyprland requires at least one match field.
pub fn generate(rules: &[Rule]) -> String {
    let mut out = String::from(HEADER);
    out.push('\n');
    for rule in rules {
        if rule.matcher.is_empty() {
            continue;
        }
        out.push_str(&render_rule(rule));
        out.push('\n');
    }
    out
}

fn render_rule(rule: &Rule) -> String {
    let mut fields = Vec::new();
    fields.push(format!("name = {}", lua_string(&rule.name)));
    fields.push(format!("enabled = {}", rule.enabled));
    fields.push(format!("match = {}", render_matcher(&rule.matcher)));

    let e = &rule.effects;
    if !e.workspace.is_empty() {
        fields.push(format!(
            "workspace = {}",
            lua_string(&e.workspace.to_lua_value())
        ));
    }
    if let Some(v) = &e.tag {
        fields.push(format!("tag = {}", lua_string(v)));
    }
    if let Some(v) = e.float {
        fields.push(format!("float = {v}"));
    }
    if let Some([x, y]) = &e.r#move {
        fields.push(format!("move = {{ {}, {} }}", lua_expr(x), lua_expr(y)));
    }
    if let Some([w, h]) = &e.size {
        fields.push(format!("size = {{ {}, {} }}", lua_expr(w), lua_expr(h)));
    }
    if !e.opacity.is_empty() {
        fields.push(format!("opacity = {}", lua_string(&e.opacity.to_lua_value())));
    }
    if let Some(color) = &e.border_color {
        fields.push(format!("border_color = {}", lua_string(color)));
    }
    if let Some(v) = e.no_blur {
        fields.push(format!("no_blur = {v}"));
    }
    if let Some(v) = e.rounding {
        fields.push(format!("rounding = {v}"));
    }

    format!("hl.window_rule({{ {} }})\n", fields.join(", "))
}

fn render_matcher(m: &crate::model::Matcher) -> String {
    let mut parts = Vec::new();
    if let Some(v) = &m.class {
        parts.push(format!("class = {}", lua_string(v)));
    }
    if let Some(v) = &m.title {
        parts.push(format!("title = {}", lua_string(v)));
    }
    if let Some(v) = &m.initial_class {
        parts.push(format!("initial_class = {}", lua_string(v)));
    }
    if let Some(v) = &m.initial_title {
        parts.push(format!("initial_title = {}", lua_string(v)));
    }
    if let Some(v) = m.fullscreen {
        parts.push(format!("fullscreen = {v}"));
    }
    if let Some(v) = m.floating {
        // Hyprland spells the *matcher* `float`, same as the effect — there
        // is no `floating` match property, and emitting one aborts the whole
        // file with "unknown match property", taking every other rule in it
        // down too. The model keeps `floating` because that's the TOML key
        // users may already have written, and because `Effects::float` next
        // to a `Matcher::float` would read as the same thing.
        parts.push(format!("float = {v}"));
    }
    if let Some(v) = m.xwayland {
        parts.push(format!("xwayland = {v}"));
    }
    if let Some(v) = &m.tag {
        parts.push(format!("tag = {}", lua_string(v)));
    }
    if let Some(v) = &m.content {
        parts.push(format!("content = {}", lua_string(v)));
    }
    format!("{{ {} }}", parts.join(", "))
}

/// A literal numeric/pixel expression is emitted bare; anything else
/// (Hyprland move/size expression strings like `"cursor_x-(window_w*0.5)"`)
/// is quoted.
fn lua_expr(s: &str) -> String {
    if s.parse::<f64>().is_ok() {
        s.to_string()
    } else {
        lua_string(s)
    }
}

/// Quotes `s` using a Lua long-bracket string (`[[...]]`), which needs no
/// escaping and so passes RE2 regex strings through verbatim. Falls back to
/// a `[=[...]=]` level if the content itself contains `]]`.
fn lua_string(s: &str) -> String {
    if !s.contains("]]") {
        format!("[[{s}]]")
    } else {
        format!("[=[{s}]=]")
    }
}
