//! Renders the owned settings as a single `hl.config` call.
//!
//! Two measured facts about `hl.config` shape everything here (Hyprland
//! 0.56.1, checked with `hyprctl eval` and `hyprctl getoption`):
//!
//! 1. **A call updates only the keys it is passed.** Passing
//!    `{ input = { repeat_delay = 601 } }` left `input:kb_layout` exactly as
//!    the user's own config had set it. So emitting only owned keys really
//!    does leave everything else alone — this file is an overlay, not a
//!    replacement.
//! 2. **A later call wins over an earlier one.** `repeat_delay` went from
//!    600 to 601 and `set` flipped to true. That is why
//!    [`crate::setup::PLACEMENT`] is `AtEnd` and not `BeforeUserRequires`
//!    like window rules: sourced first, every setting saved in the app
//!    would be silently overwritten by the user's own `hl.config` block,
//!    and the app would report a successful save that changed nothing.

use crate::catalog;
use crate::model::{Settings, Value};
use hyprforge_core::lua::lua_string;
use std::collections::BTreeMap;

const HEADER: &str = "-- Generated by Hyprforge. Do not edit by hand — changes will be\n-- overwritten the next time an input setting is saved in the Hyprforge\n-- Settings app.\n";

/// A node in the nested table `hl.config` takes. Ordered so the output is
/// byte-stable between runs.
#[derive(Default)]
struct Table<'a> {
    leaves: BTreeMap<&'a str, String>,
    children: BTreeMap<&'a str, Table<'a>>,
}

impl<'a> Table<'a> {
    fn insert(&mut self, path: &[&'a str], rendered: String) {
        match path {
            [] => {}
            [leaf] => {
                self.leaves.insert(leaf, rendered);
            }
            [head, rest @ ..] => {
                self.children.entry(head).or_default().insert(rest, rendered);
            }
        }
    }

    fn is_empty(&self) -> bool {
        self.leaves.is_empty() && self.children.is_empty()
    }

    fn render(&self, indent: usize) -> String {
        let pad = "    ".repeat(indent);
        let mut out = String::new();
        for (name, value) in &self.leaves {
            out.push_str(&format!("{pad}{name} = {value},\n"));
        }
        for (name, child) in &self.children {
            out.push_str(&format!("{pad}{name} = {{\n"));
            out.push_str(&child.render(indent + 1));
            out.push_str(&format!("{pad}}},\n"));
        }
        out
    }
}

/// Renders a complete `input.lua` body.
///
/// Values the catalog rejects are skipped rather than emitted. A stored
/// value that would break the file is one a hand-edit can produce, and
/// writing it out would take the user's whole config down over a typo in a
/// setting they could otherwise just fix; the editor surfaces the same
/// problems through [`Settings::validate`] so nothing is skipped silently.
pub fn generate(settings: &Settings) -> String {
    let mut root = Table::default();
    for (key, value) in &settings.values {
        let Some(setting) = catalog::get(key) else {
            continue;
        };
        if !crate::model::Settings::from_one(key, value.clone())
            .validate()
            .is_empty()
        {
            continue;
        }
        let path: Vec<&str> = setting.key.split(':').collect();
        root.insert(&path, render_value(value));
    }

    let mut out = String::from(HEADER);
    if root.is_empty() {
        // Still a valid, loadable file: `require()` of a missing or
        // syntactically empty file is an error, and the setup step writes
        // this same body before anything has been configured.
        return out;
    }
    out.push('\n');
    out.push_str("hl.config({\n");
    out.push_str(&root.render(1));
    out.push_str("})\n");
    out
}

fn render_value(value: &Value) -> String {
    match value {
        Value::Bool(b) => b.to_string(),
        Value::Int(i) => i.to_string(),
        // Always with a decimal point, so a float setting never reaches
        // Hyprland looking like an integer.
        //
        // Only finite floats get here — `generate` skips anything
        // `validate` rejects, and non-finite is one of the things it
        // rejects precisely because `NaN` renders as `NaN.0`, which is a
        // syntax error that would take the whole file down. Debug
        // formatting of a finite f64 always carries a `.` or an `e`, so
        // the fallback is belt and braces.
        Value::Float(f) => {
            let s = format!("{f:?}");
            if s.contains(['.', 'e']) {
                s
            } else {
                format!("{s}.0")
            }
        }
        Value::Text(s) => lua_string(s),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn settings(pairs: &[(&str, Value)]) -> Settings {
        let mut s = Settings::default();
        for (k, v) in pairs {
            s.set(k, v.clone());
        }
        s
    }

    #[test]
    fn an_empty_set_is_still_a_loadable_file() {
        let out = generate(&Settings::default());
        assert!(out.starts_with("-- Generated by Hyprforge"));
        assert!(!out.contains("hl.config"));
    }

    #[test]
    fn top_level_settings_go_under_input() {
        let out = generate(&settings(&[
            ("input:kb_layout", Value::Text("us,cz".into())),
            ("input:repeat_rate", Value::Int(30)),
        ]));
        assert!(out.contains("hl.config({\n    input = {\n"), "{out}");
        assert!(out.contains("kb_layout = [[us,cz]],"), "{out}");
        assert!(out.contains("repeat_rate = 30,"), "{out}");
    }

    #[test]
    fn a_subcategory_nests_inside_its_parent() {
        let out = generate(&settings(&[(
            "input:touchpad:tap_to_click",
            Value::Bool(true),
        )]));
        assert!(
            out.contains("input = {\n        touchpad = {\n            tap_to_click = true,\n"),
            "{out}"
        );
    }

    /// Both levels in one call, which is the shape a real settings file
    /// takes and the one most likely to come out malformed.
    #[test]
    fn leaves_and_subcategories_coexist_in_one_call() {
        let out = generate(&settings(&[
            ("input:kb_layout", Value::Text("us".into())),
            ("input:touchpad:natural_scroll", Value::Bool(true)),
        ]));
        assert_eq!(out.matches("hl.config").count(), 1, "{out}");
        assert!(out.contains("kb_layout = [[us]],"), "{out}");
        assert!(out.contains("natural_scroll = true,"), "{out}");
    }

    /// A float that happens to be whole must not render as `1`, so a
    /// setting Hyprland types as a float never arrives as an integer.
    #[test]
    fn a_whole_float_keeps_its_decimal_point() {
        let out = generate(&settings(&[(
            "input:touchpad:scroll_factor",
            Value::Float(1.0),
        )]));
        assert!(out.contains("scroll_factor = 1.0,"), "{out}");
    }

    #[test]
    fn text_is_quoted_through_the_shared_lua_helper() {
        let out = generate(&settings(&[(
            "input:kb_options",
            Value::Text("grp:alt_shift_toggle".into()),
        )]));
        assert!(out.contains("kb_options = [[grp:alt_shift_toggle]],"), "{out}");
    }

    /// The whole point of the overlay: a file holding one key mentions
    /// exactly one key, so every other input option is still the user's.
    #[test]
    fn only_owned_keys_appear() {
        let out = generate(&settings(&[("input:repeat_rate", Value::Int(30))]));
        assert!(!out.contains("kb_layout"), "{out}");
        assert!(!out.contains("touchpad"), "{out}");
    }

    /// A hand-edited TOML can hold a value the catalog refuses. Emitting it
    /// would take the user's entire config down; the editor reports it
    /// separately, so skipping here isn't silent.
    #[test]
    fn an_invalid_value_is_skipped_rather_than_written() {
        let out = generate(&settings(&[
            ("input:sensitivity", Value::Float(99.0)),
            ("input:repeat_rate", Value::Int(30)),
        ]));
        assert!(!out.contains("sensitivity"), "{out}");
        assert!(out.contains("repeat_rate = 30,"), "{out}");
    }

    #[test]
    fn an_unknown_key_is_skipped() {
        let out = generate(&settings(&[("input:not_real", Value::Int(1))]));
        assert!(!out.contains("not_real"), "{out}");
    }

    /// Same input, same bytes — otherwise every save churns the file and a
    /// real change becomes impossible to spot in a diff.
    #[test]
    fn output_is_stable_across_runs() {
        let s = settings(&[
            ("input:touchpad:tap_to_click", Value::Bool(true)),
            ("input:kb_layout", Value::Text("us".into())),
            ("input:repeat_rate", Value::Int(30)),
        ]);
        assert_eq!(generate(&s), generate(&s));
    }
}
