[package]
name = "hyprforge-settings"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hyprforge-core = { workspace = true, features = ["dbus"] }
hyprforge-windowrules.workspace = true
iced.workspace = true
zbus.workspace = true
tokio.workspace = true
futures-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
