//! Renders the owned settings as a single `hl.config` call.
//!
//! Two measured facts about `hl.config` shape everything here (Hyprland
//! 0.56.1, checked with `hyprctl eval` and `hyprctl getoption`):
//!
//! 1. **A call updates only the keys it is passed.** Passing
//!    `{ input = { repeat_delay = 601 } }` left `input:kb_layout` exactly as
//!    the user's own config had set it. So emitting only owned keys really
//!    does leave everything else alone — this file is an overlay, not a
//!    replacement.
//! 2. **A later call wins over an earlier one.** `repeat_delay` went from
//!    600 to 601 and `set` flipped to true. That is why
//!    `PLACEMENT` is `AtEnd` and not `BeforeUserRequires`
//!    like window rules: sourced first, every setting saved in the app
//!    would be silently overwritten by the user's own `hl.config` block,
//!    and the app would report a successful save that changed nothing.

use super::{Catalog, Settings, Value};
use crate::lua::lua_string;
use std::collections::BTreeMap;


/// A node in the nested table `hl.config` takes. Ordered so the output is
/// byte-stable between runs.
#[derive(Default)]
struct Table<'a> {
    leaves: BTreeMap<&'a str, String>,
    children: BTreeMap<&'a str, Table<'a>>,
}

impl<'a> Table<'a> {
    fn insert(&mut self, path: &[&'a str], rendered: String) {
        match path {
            [] => {}
            [leaf] => {
                self.leaves.insert(leaf, rendered);
            }
            [head, rest @ ..] => {
                self.children.entry(head).or_default().insert(rest, rendered);
            }
        }
    }

    fn is_empty(&self) -> bool {
        self.leaves.is_empty() && self.children.is_empty()
    }

    fn render(&self, indent: usize) -> String {
        let pad = "    ".repeat(indent);
        let mut out = String::new();
        for (name, value) in &self.leaves {
            out.push_str(&format!("{pad}{name} = {value},\n"));
        }
        for (name, child) in &self.children {
            out.push_str(&format!("{pad}{name} = {{\n"));
            out.push_str(&child.render(indent + 1));
            out.push_str(&format!("{pad}}},\n"));
        }
        out
    }
}

/// Renders a complete `input.lua` body.
///
/// Values the catalog rejects are skipped rather than emitted. A stored
/// value that would break the file is one a hand-edit can produce, and
/// writing it out would take the user's whole config down over a typo in a
/// setting they could otherwise just fix; the editor surfaces the same
/// problems through [`Settings::validate`] so nothing is skipped silently.
pub fn generate(settings: &Settings, catalog: &Catalog, subject: &str) -> String {
    let mut root = Table::default();
    for (key, value) in &settings.values {
        let Some(setting) = catalog.get(key) else {
            continue;
        };
        if !Settings::from_one(key, value.clone())
            .validate(catalog)
            .is_empty()
        {
            continue;
        }
        let path: Vec<&str> = setting.key.split(':').collect();
        root.insert(&path, render_value(value));
    }

    let mut out = header(subject);
    if root.is_empty() {
        // Still a valid, loadable file: `require()` of a missing or
        // syntactically empty file is an error, and the setup step writes
        // this same body before anything has been configured.
        return out;
    }
    out.push('\n');
    out.push_str("hl.config({\n");
    out.push_str(&root.render(1));
    out.push_str("})\n");
    out
}

/// The "don't edit this" banner. Takes the subject so each module's file
/// names the screen that owns it — a user who finds a generated file needs
/// to know where to go, not just that they shouldn't touch it.
fn header(subject: &str) -> String {
    format!(
        "-- Generated by Hyprforge. Do not edit by hand — changes will be\n\
         -- overwritten the next time {subject} are saved in the Hyprforge\n\
         -- Settings app.\n"
    )
}

fn render_value(value: &Value) -> String {
    match value {
        Value::Bool(b) => b.to_string(),
        Value::Int(i) => i.to_string(),
        // Always with a decimal point, so a float setting never reaches
        // Hyprland looking like an integer.
        //
        // Only finite floats get here — `generate` skips anything
        // `validate` rejects, and non-finite is one of the things it
        // rejects precisely because `NaN` renders as `NaN.0`, which is a
        // syntax error that would take the whole file down. Debug
        // formatting of a finite f64 always carries a `.` or an `e`, so
        // the fallback is belt and braces.
        Value::Float(f) => {
            let s = format!("{f:?}");
            if s.contains(['.', 'e']) {
                s
            } else {
                format!("{s}.0")
            }
        }
        Value::Text(s) => lua_string(s),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::hlconfig::model::test_catalog::CATALOG;

    fn settings(pairs: &[(&str, Value)]) -> Settings {
        let mut s = Settings::default();
        for (k, v) in pairs {
            s.set(k, v.clone());
        }
        s
    }

    fn lua(s: &Settings) -> String {
        generate(s, &CATALOG, "demo settings")
    }

    #[test]
    fn an_empty_set_is_still_a_loadable_file() {
        let out = lua(&Settings::default());
        assert!(out.starts_with("-- Generated by Hyprforge"));
        assert!(!out.contains("hl.config"));
    }

    #[test]
    fn the_header_names_the_screen_that_owns_the_file() {
        assert!(lua(&Settings::default()).contains("demo settings"));
    }

    #[test]
    fn top_level_settings_nest_under_their_category() {
        let out = lua(&settings(&[
            ("demo:name", Value::Text("hello".into())),
            ("demo:count", Value::Int(3)),
        ]));
        assert!(out.contains("hl.config({\n    demo = {\n"), "{out}");
        assert!(out.contains("name = [[hello]],"), "{out}");
        assert!(out.contains("count = 3,"), "{out}");
    }

    #[test]
    fn a_subcategory_nests_inside_its_parent() {
        let out = lua(&settings(&[("demo:nested:deep", Value::Bool(true))]));
        assert!(
            out.contains("demo = {\n        nested = {\n            deep = true,\n"),
            "{out}"
        );
    }

    /// Both levels in one call, which is the shape a real settings file
    /// takes and the one most likely to come out malformed.
    #[test]
    fn leaves_and_subcategories_coexist_in_one_call() {
        let out = lua(&settings(&[
            ("demo:name", Value::Text("x".into())),
            ("demo:nested:deep", Value::Bool(false)),
        ]));
        assert_eq!(out.matches("hl.config").count(), 1, "{out}");
        assert!(out.contains("name = [[x]],"), "{out}");
        assert!(out.contains("deep = false,"), "{out}");
    }

    /// Several top-level categories in one call — the shape a module
    /// spanning `decoration` and `general` produces.
    #[test]
    fn separate_top_level_categories_share_one_call() {
        let mut s = Settings::default();
        s.set("demo:count", Value::Int(1));
        s.set("demo:nested:deep", Value::Bool(true));
        let out = lua(&s);
        assert_eq!(out.matches("hl.config").count(), 1, "{out}");
    }

    /// A float that happens to be whole must not render as `1`, so a
    /// setting Hyprland types as a float never arrives as an integer.
    #[test]
    fn a_whole_float_keeps_its_decimal_point() {
        let out = lua(&settings(&[("demo:ratio", Value::Float(1.0))]));
        assert!(out.contains("ratio = 1.0,"), "{out}");
    }

    #[test]
    fn text_is_quoted_through_the_shared_lua_helper() {
        let out = lua(&settings(&[("demo:name", Value::Text("a:b".into()))]));
        assert!(out.contains("name = [[a:b]],"), "{out}");
    }

    /// The whole point of the overlay: a file holding one key mentions
    /// exactly one key, so every other setting is still the user's.
    #[test]
    fn only_owned_keys_appear() {
        let out = lua(&settings(&[("demo:count", Value::Int(3))]));
        assert!(!out.contains("name"), "{out}");
        assert!(!out.contains("nested"), "{out}");
    }

    /// A hand-edited TOML can hold a value the catalog refuses. Emitting
    /// it would take the user's entire config down; the editor reports it
    /// separately, so skipping here isn't silent.
    #[test]
    fn an_invalid_value_is_skipped_rather_than_written() {
        let out = lua(&settings(&[
            ("demo:ratio", Value::Float(99.0)),
            ("demo:count", Value::Int(3)),
        ]));
        assert!(!out.contains("ratio"), "{out}");
        assert!(out.contains("count = 3,"), "{out}");
    }

    #[test]
    fn an_unknown_key_is_skipped() {
        assert!(!lua(&settings(&[("demo:not_real", Value::Int(1))])).contains("not_real"));
    }

    /// Same input, same bytes — otherwise every save churns the file and
    /// a real change becomes impossible to spot in a diff.
    #[test]
    fn output_is_stable_across_runs() {
        let s = settings(&[
            ("demo:nested:deep", Value::Bool(true)),
            ("demo:name", Value::Text("x".into())),
            ("demo:count", Value::Int(3)),
        ]);
        assert_eq!(lua(&s), lua(&s));
    }
}
