//! Where Hyprforge's *Hyprland* files live.
//!
//! The generic answers — which directory is mine, how do I write a file
//! atomically — moved to `hyprforge-paths`, so that an app with no
//! interest in Hyprland can have them without this crate. They are
//! re-exported here so the ~70 existing call sites keep working.

use std::path::PathBuf;

pub use hyprforge_paths::{config_home, hyprforge_config_dir, write_atomic};


/// `$XDG_CONFIG_HOME/hypr` — the user's own Hyprland config directory.
/// Hyprforge only ever writes to `hypr/hyprforge/` inside this, and only
/// touches `hyprland.lua` itself via the explicit, confirmed one-time
/// `require()` insertion.
pub fn hypr_config_dir() -> PathBuf {
    config_home().join("hypr")
}

/// `$XDG_CONFIG_HOME/hypr/hyprforge` — generated Lua artifacts live here,
/// sourced from the user's `hyprland.lua` via `require("hyprforge/...")`.
pub fn hypr_hyprforge_dir() -> PathBuf {
    hypr_config_dir().join("hyprforge")
}

pub fn display_profiles_path() -> PathBuf {
    hyprforge_config_dir().join("display-profiles.toml")
}

pub fn window_rules_toml_path() -> PathBuf {
    hyprforge_config_dir().join("window-rules.toml")
}

pub fn window_rules_lua_path() -> PathBuf {
    hypr_hyprforge_dir().join("window-rules.lua")
}

pub fn input_toml_path() -> PathBuf {
    hyprforge_config_dir().join("input.toml")
}

pub fn input_lua_path() -> PathBuf {
    hypr_hyprforge_dir().join("input.lua")
}

pub fn hyprland_lua_path() -> PathBuf {
    hypr_config_dir().join("hyprland.lua")
}

pub fn shortcuts_toml_path() -> PathBuf {
    hyprforge_config_dir().join("shortcuts.toml")
}

pub fn keybinds_lua_path() -> PathBuf {
    hypr_hyprforge_dir().join("keybinds.lua")
}

/// The static, Hyprland-native fallback: `hl.monitor()` calls reflecting
/// whatever layout is currently live, regenerated by the daemon on every
/// settled topology. Unlike the daemon's runtime application over
/// `wlr-output-management-v1`, Hyprland applies this file itself on its own
/// startup/reload, so a saved layout survives even when the daemon isn't
/// running to reassert it.
pub fn monitors_lua_path() -> PathBuf {
    hypr_hyprforge_dir().join("monitors.lua")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Mutex, MutexGuard};

    /// `set_var`/`remove_var` are process-global and Rust runs tests on
    /// threads, so every test that touches the environment has to take this
    /// first or they corrupt each other's reads.
    static ENV_LOCK: Mutex<()> = Mutex::new(());

    /// Sets the two variables `config_home` reads, restoring whatever was
    /// there when the guard drops — otherwise a test would leak its fake
    /// `$HOME` into every test that runs after it.
    struct EnvGuard {
        _lock: MutexGuard<'static, ()>,
        xdg: Option<std::ffi::OsString>,
        home: Option<std::ffi::OsString>,
    }

    impl EnvGuard {
        fn set(xdg: Option<&str>, home: Option<&str>) -> Self {
            let guard = EnvGuard {
                _lock: ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner()),
                xdg: std::env::var_os("XDG_CONFIG_HOME"),
                home: std::env::var_os("HOME"),
            };
            // SAFETY: ENV_LOCK serializes every env mutation in this module.
            unsafe {
                match xdg {
                    Some(v) => std::env::set_var("XDG_CONFIG_HOME", v),
                    None => std::env::remove_var("XDG_CONFIG_HOME"),
                }
                match home {
                    Some(v) => std::env::set_var("HOME", v),
                    None => std::env::remove_var("HOME"),
                }
            }
            guard
        }
    }

    impl Drop for EnvGuard {
        fn drop(&mut self) {
            unsafe {
                match &self.xdg {
                    Some(v) => std::env::set_var("XDG_CONFIG_HOME", v),
                    None => std::env::remove_var("XDG_CONFIG_HOME"),
                }
                match &self.home {
                    Some(v) => std::env::set_var("HOME", v),
                    None => std::env::remove_var("HOME"),
                }
            }
        }
    }

    #[test]
    fn derived_paths_all_hang_off_config_home() {
        let _g = EnvGuard::set(Some("/custom/config"), Some("/home/someone"));
        assert_eq!(
            display_profiles_path(),
            PathBuf::from("/custom/config/hyprforge/display-profiles.toml")
        );
        assert_eq!(
            window_rules_toml_path(),
            PathBuf::from("/custom/config/hyprforge/window-rules.toml")
        );
        // The generated Lua lives under hypr/, not hyprforge/, because
        // Hyprland's require() resolves relative to its own config dir.
        assert_eq!(
            window_rules_lua_path(),
            PathBuf::from("/custom/config/hypr/hyprforge/window-rules.lua")
        );
        assert_eq!(
            hyprland_lua_path(),
            PathBuf::from("/custom/config/hypr/hyprland.lua")
        );
        assert_eq!(
            shortcuts_toml_path(),
            PathBuf::from("/custom/config/hyprforge/shortcuts.toml")
        );
        assert_eq!(
            keybinds_lua_path(),
            PathBuf::from("/custom/config/hypr/hyprforge/keybinds.lua")
        );
        assert_eq!(
            monitors_lua_path(),
            PathBuf::from("/custom/config/hypr/hyprforge/monitors.lua")
        );
    }
}
