#!/usr/bin/env python3
"""Render the AUR's PKGBUILD from packaging/arch/PKGBUILD.

    tools/aur.py --write   rewrite packaging/aur/hyprforge/ (PKGBUILD, the
                           .install scriptlets, and .SRCINFO via makepkg)
    tools/aur.py --check   exit 1 naming whatever differs from a fresh render
    tools/aur.py --local-into DIR
                           the same render, fetching from this checkout's
                           committed HEAD and its submodule clones instead
                           of GitHub — what check.sh's clean-chroot tier
                           builds, since the published tag is not what
                           is being checked

packaging/arch/PKGBUILD builds the checkout it sits in: `source=()`, and
every function starts with `cd "$startdir/../.."`. That is right for a
developer and useless to the AUR, where makepkg starts in an empty
directory and has to fetch the code itself. Rather than keep a second
PKGBUILD by hand — which would drift in exactly the way the standalone
crates' dependency pins did, with nothing failing — this renders one
from the other, and check.sh fails if the committed copy is not what
this would write. Edit packaging/arch/PKGBUILD; never the rendered copy.

What the render changes, and nothing else:

- `source=()` becomes the suite at `#tag=v$pkgver` plus every component
  repository named in .gitmodules. GitHub's source tarballs leave
  submodules out, so a tarball cannot be the source.
- `prepare` stops running `git submodule update --init` against the
  network, which makepkg's model does not allow: it points each
  submodule's URL at the copy makepkg already fetched into `$srcdir`,
  the pattern the Arch wiki gives for VCS sources with submodules.
- `$startdir/../..` becomes `$srcdir/hyprforge`, where makepkg extracts
  the suite.

The render is only buildable when the tag `v$pkgver` carries the same
packaging as this checkout: a package function that installs a file the
tagged tree does not have fails at build time, and nothing here can see
that. `tools/release.sh` renders at release time, from the commit it
tags, for that reason.
"""

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "packaging" / "arch"
OUT = ROOT / "packaging" / "aur" / "hyprforge"
SUITE_URL = "https://github.com/hyprforge-suite/hyprforge.git"

HEADER = """\
# GENERATED by tools/aur.py from packaging/arch/PKGBUILD — do not edit.
# Edit that file and run `tools/aur.py --write`; check.sh's "AUR PKGBUILD
# matches packaging/arch" fails on any difference.
"""

PREPARE_OLD = """\
  # The components are submodules of this repository; a checkout made
  # without --recurse-submodules has their directories empty, and the
  # workspace below would not load.
  git submodule update --init
"""


def submodules():
    out = subprocess.run(
        ["git", "config", "-f", ".gitmodules", "--get-regexp", r"submodule\..*\.(path|url)"],
        cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout
    found = {}
    for line in out.splitlines():
        key, value = line.split(maxsplit=1)
        name, field = key[len("submodule."):].rsplit(".", 1)
        found.setdefault(name, {})[field] = value
    return sorted((v["path"], v["url"]) for v in found.values())


def render(text, local=False):
    subs = submodules()
    if "source=()" not in text:
        raise SystemExit("packaging/arch/PKGBUILD has no `source=()` line to replace")
    if PREPARE_OLD not in text:
        raise SystemExit("packaging/arch/PKGBUILD's prepare() changed shape; update tools/aur.py")

    if local:
        head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()
        sources = [f'  "hyprforge::git+file://{ROOT}#commit={head}"']
        for path, _ in subs:
            sources.append(f'  "{Path(path).name}::git+file://{ROOT / path}"')
    else:
        sources = [f'  "hyprforge::git+{SUITE_URL}#tag=v$pkgver"']
        for path, url in subs:
            sources.append(f'  "{Path(path).name}::git+{url}"')
    source = "source=(\n" + "\n".join(sources) + "\n)\nsha256sums=(" + " ".join(["'SKIP'"] * len(sources)) + ")"
    text = text.replace("source=()", source, 1)

    wiring = [
        "  # The components are submodules of the suite. makepkg has already",
        "  # fetched each one into $srcdir (see source=), so point every",
        "  # submodule at that copy instead of the network, then check out the",
        "  # commit the tagged suite pins.",
        "  git submodule init",
    ]
    for path, _ in subs:
        wiring.append(f'  git config submodule.{path}.url "$srcdir/{Path(path).name}"')
    wiring.append("  git -c protocol.file.allow=always submodule update")
    text = text.replace(PREPARE_OLD, "\n".join(wiring) + "\n", 1)

    text = text.replace('cd "$startdir/../.."', 'cd "$srcdir/hyprforge"')
    text = text.replace('"$startdir/../../', '"$srcdir/hyprforge/')
    if "$startdir" in text:
        line = next(l for l in text.splitlines() if "$startdir" in l)
        raise SystemExit(f"a $startdir the render does not know how to rewrite: {line.strip()}")
    return HEADER + text


def expected():
    """{relative path: text} of everything the render owns, .SRCINFO aside."""
    files = {"PKGBUILD": render((SRC / "PKGBUILD").read_text())}
    for script in sorted(SRC.glob("*.install")):
        files[script.name] = script.read_text()
    return files


def srcinfo(directory):
    if not shutil.which("makepkg"):
        return None
    return subprocess.run(
        ["makepkg", "--printsrcinfo"], cwd=directory, capture_output=True, text=True, check=True
    ).stdout


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--local-into", metavar="DIR", type=Path)
    args = ap.parse_args()
    files = expected()

    if args.local_into:
        args.local_into.mkdir(parents=True, exist_ok=True)
        files["PKGBUILD"] = render((SRC / "PKGBUILD").read_text(), local=True)
        for name, text in files.items():
            (args.local_into / name).write_text(text)
        print(f"wrote a local render into {args.local_into}")
        return

    if args.write:
        OUT.mkdir(parents=True, exist_ok=True)
        for stale in OUT.glob("*.install"):
            if stale.name not in files:
                stale.unlink()
        for name, text in files.items():
            (OUT / name).write_text(text)
        info = srcinfo(OUT)
        if info is None:
            print("makepkg not found: .SRCINFO not regenerated", file=sys.stderr)
            sys.exit(1)
        (OUT / ".SRCINFO").write_text(info)
        print(f"wrote {OUT.relative_to(ROOT)} ({len(files)} file(s) and .SRCINFO)")
        return

    stale = []
    for name, text in files.items():
        path = OUT / name
        if not path.exists() or path.read_text() != text:
            stale.append(name)
    for extra in OUT.glob("*.install"):
        if extra.name not in files:
            stale.append(f"{extra.name} (no longer in packaging/arch)")
    info = srcinfo(OUT) if OUT.exists() else None
    srcinfo_path = OUT / ".SRCINFO"
    if info is not None and (not srcinfo_path.exists() or srcinfo_path.read_text() != info):
        stale.append(".SRCINFO")
    for name in stale:
        print(f"STALE {name}")
    if info is None:
        print("NOSRCINFO makepkg not found: .SRCINFO not compared")
    sys.exit(1 if stale else 0)


if __name__ == "__main__":
    main()
